2020-03-16 14:57:47,139 - [test_register.py-->line:36] - ERROR:用例:注册成功-带注册名,执行未通过
2020-03-16 14:57:47,139 - [test_register.py-->line:37] - ERROR:0 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 32, in test_register
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2020-03-16 14:57:47,256 - [test_register.py-->line:36] - ERROR:用例:成功-不带用户名,执行未通过
2020-03-16 14:57:47,257 - [test_register.py-->line:37] - ERROR:0 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 32, in test_register
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2020-03-16 14:57:47,402 - [test_register.py-->line:42] - INFO:用例:不输入手机号,执行通过
2020-03-16 14:57:47,528 - [test_register.py-->line:42] - INFO:用例:手机号长度10位,执行通过
2020-03-16 14:57:47,668 - [test_register.py-->line:42] - INFO:用例:手机号长度12位,执行通过
2020-03-16 14:57:47,821 - [test_register.py-->line:42] - INFO:用例:手机号含有非法字符,执行通过
2020-03-16 14:57:47,985 - [test_register.py-->line:42] - INFO:用例:已注册过的手机号,执行通过
2020-03-16 14:57:48,140 - [test_register.py-->line:42] - INFO:用例:密码7位,执行通过
2020-03-16 14:57:48,400 - [test_register.py-->line:42] - INFO:用例:密码17位,执行通过
2020-03-16 14:57:48,526 - [test_register.py-->line:42] - INFO:用例:不输入密码,执行通过
2020-03-16 14:57:48,649 - [test_register.py-->line:36] - ERROR:用例:注册名11位,执行未通过
2020-03-16 14:57:48,650 - [test_register.py-->line:37] - ERROR:'用户昵称长度超过10位' != '无效的手机格式'
- 用户昵称长度超过10位
+ 无效的手机格式
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 33, in test_register
    self.assertEqual(expected["msg"],res["msg"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 1292, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python3\lib\unittest\case.py", line 753, in fail
    raise self.failureException(msg)
AssertionError: '用户昵称长度超过10位' != '无效的手机格式'
- 用户昵称长度超过10位
+ 无效的手机格式

2020-03-16 14:57:48,854 - [test_register.py-->line:36] - ERROR:用例:类型输入非0，1内容,执行未通过
2020-03-16 14:57:48,855 - [test_register.py-->line:37] - ERROR:'不支持的用户类型' != '无效的手机格式'
- 不支持的用户类型
+ 无效的手机格式
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 33, in test_register
    self.assertEqual(expected["msg"],res["msg"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 1292, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\python3\lib\unittest\case.py", line 753, in fail
    raise self.failureException(msg)
AssertionError: '不支持的用户类型' != '无效的手机格式'
- 不支持的用户类型
+ 无效的手机格式

2020-03-16 14:57:49,005 - [test_register.py-->line:36] - ERROR:用例:不输入类型,执行未通过
2020-03-16 14:57:49,006 - [test_register.py-->line:37] - ERROR:0 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 32, in test_register
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2020-03-16 15:01:06,688 - [test_register.py-->line:42] - INFO:用例:注册成功-带注册名,执行通过
2020-03-16 15:01:07,408 - [test_register.py-->line:42] - INFO:用例:成功-不带用户名,执行通过
2020-03-16 15:01:07,839 - [test_register.py-->line:42] - INFO:用例:不输入手机号,执行通过
2020-03-16 15:01:08,181 - [test_register.py-->line:42] - INFO:用例:手机号长度10位,执行通过
2020-03-16 15:01:08,943 - [test_register.py-->line:42] - INFO:用例:手机号长度12位,执行通过
2020-03-16 15:01:09,214 - [test_register.py-->line:42] - INFO:用例:手机号含有非法字符,执行通过
2020-03-16 15:01:09,775 - [test_register.py-->line:42] - INFO:用例:已注册过的手机号,执行通过
2020-03-16 15:01:10,082 - [test_register.py-->line:42] - INFO:用例:密码7位,执行通过
2020-03-16 15:01:10,596 - [test_register.py-->line:42] - INFO:用例:密码17位,执行通过
2020-03-16 15:01:10,995 - [test_register.py-->line:42] - INFO:用例:不输入密码,执行通过
2020-03-16 15:01:11,325 - [test_register.py-->line:42] - INFO:用例:注册名11位,执行通过
2020-03-16 15:01:11,549 - [test_register.py-->line:42] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-16 15:01:11,868 - [test_register.py-->line:42] - INFO:用例:不输入类型,执行通过
2020-03-16 15:17:57,782 - [test_register.py-->line:36] - ERROR:用例:注册成功-带注册名,执行未通过
2020-03-16 15:17:57,782 - [test_register.py-->line:37] - ERROR:0 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 32, in test_register
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2020-03-16 15:17:57,935 - [test_register.py-->line:36] - ERROR:用例:成功-不带用户名,执行未通过
2020-03-16 15:17:57,935 - [test_register.py-->line:37] - ERROR:0 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 32, in test_register
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2020-03-16 15:17:58,071 - [test_register.py-->line:42] - INFO:用例:不输入手机号,执行通过
2020-03-16 15:17:58,213 - [test_register.py-->line:42] - INFO:用例:手机号长度10位,执行通过
2020-03-16 15:17:58,355 - [test_register.py-->line:42] - INFO:用例:手机号长度12位,执行通过
2020-03-16 15:17:58,496 - [test_register.py-->line:42] - INFO:用例:手机号含有非法字符,执行通过
2020-03-16 15:17:58,623 - [test_register.py-->line:42] - INFO:用例:已注册过的手机号,执行通过
2020-03-16 15:17:58,748 - [test_register.py-->line:42] - INFO:用例:密码7位,执行通过
2020-03-16 15:17:58,876 - [test_register.py-->line:42] - INFO:用例:密码17位,执行通过
2020-03-16 15:17:58,989 - [test_register.py-->line:42] - INFO:用例:不输入密码,执行通过
2020-03-16 15:17:59,103 - [test_register.py-->line:42] - INFO:用例:注册名11位,执行通过
2020-03-16 15:17:59,256 - [test_register.py-->line:42] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-16 15:17:59,410 - [test_register.py-->line:36] - ERROR:用例:不输入类型,执行未通过
2020-03-16 15:17:59,411 - [test_register.py-->line:37] - ERROR:0 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 32, in test_register
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2020-03-16 15:59:52,816 - [test_register.py-->line:65] - ERROR:用例:登录成功,执行未通过
2020-03-16 15:59:52,816 - [test_register.py-->line:66] - ERROR:0 != 1001
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 61, in test_register
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 1001
2020-03-16 15:59:52,946 - [test_register.py-->line:65] - ERROR:用例:手机号为空,执行未通过
2020-03-16 15:59:52,946 - [test_register.py-->line:66] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 61, in test_register
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-16 15:59:53,137 - [test_register.py-->line:65] - ERROR:用例:密码为空,执行未通过
2020-03-16 15:59:53,137 - [test_register.py-->line:66] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 61, in test_register
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-16 15:59:53,354 - [test_register.py-->line:71] - INFO:用例:手机号未注册,执行通过
2020-03-16 15:59:53,607 - [test_register.py-->line:71] - INFO:用例:密码错误,执行通过
2020-03-16 15:59:53,853 - [test_register.py-->line:71] - INFO:用例:手机号格式错误,执行通过
2020-03-16 15:59:54,391 - [test_register.py-->line:36] - ERROR:用例:注册成功-带注册名,执行未通过
2020-03-16 15:59:54,391 - [test_register.py-->line:37] - ERROR:0 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 32, in test_register
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2020-03-16 15:59:54,581 - [test_register.py-->line:36] - ERROR:用例:成功-不带用户名,执行未通过
2020-03-16 15:59:54,581 - [test_register.py-->line:37] - ERROR:0 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 32, in test_register
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2020-03-16 15:59:54,867 - [test_register.py-->line:42] - INFO:用例:不输入手机号,执行通过
2020-03-16 15:59:55,540 - [test_register.py-->line:42] - INFO:用例:手机号长度10位,执行通过
2020-03-16 15:59:55,838 - [test_register.py-->line:42] - INFO:用例:手机号长度12位,执行通过
2020-03-16 15:59:56,068 - [test_register.py-->line:42] - INFO:用例:手机号含有非法字符,执行通过
2020-03-16 15:59:56,284 - [test_register.py-->line:42] - INFO:用例:已注册过的手机号,执行通过
2020-03-16 15:59:56,614 - [test_register.py-->line:42] - INFO:用例:密码7位,执行通过
2020-03-16 15:59:57,013 - [test_register.py-->line:42] - INFO:用例:密码17位,执行通过
2020-03-16 15:59:57,535 - [test_register.py-->line:42] - INFO:用例:不输入密码,执行通过
2020-03-16 15:59:57,670 - [test_register.py-->line:42] - INFO:用例:注册名11位,执行通过
2020-03-16 15:59:58,207 - [test_register.py-->line:42] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-16 15:59:58,701 - [test_register.py-->line:36] - ERROR:用例:不输入类型,执行未通过
2020-03-16 15:59:58,702 - [test_register.py-->line:37] - ERROR:0 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 32, in test_register
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2020-03-16 16:43:37,193 - [test_register.py-->line:72] - ERROR:用例:登录成功,执行未通过
2020-03-16 16:43:37,194 - [test_register.py-->line:73] - ERROR:0 != 1001
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 68, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 1001
2020-03-16 16:43:37,429 - [test_register.py-->line:72] - ERROR:用例:手机号为空,执行未通过
2020-03-16 16:43:37,429 - [test_register.py-->line:73] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 68, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-16 16:43:37,700 - [test_register.py-->line:72] - ERROR:用例:密码为空,执行未通过
2020-03-16 16:43:37,701 - [test_register.py-->line:73] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 68, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-16 16:43:37,886 - [test_register.py-->line:78] - INFO:用例:手机号未注册,执行通过
2020-03-16 16:43:38,071 - [test_register.py-->line:78] - INFO:用例:密码错误,执行通过
2020-03-16 16:43:38,232 - [test_register.py-->line:78] - INFO:用例:手机号格式错误,执行通过
2020-03-16 16:44:29,587 - [test_register.py-->line:77] - ERROR:用例:登录成功,执行未通过
2020-03-16 16:44:29,587 - [test_register.py-->line:78] - ERROR:0 != 1001
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 1001
2020-03-16 16:44:29,770 - [test_register.py-->line:77] - ERROR:用例:手机号为空,执行未通过
2020-03-16 16:44:29,771 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-16 16:44:30,036 - [test_register.py-->line:77] - ERROR:用例:密码为空,执行未通过
2020-03-16 16:44:30,036 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-16 16:44:30,276 - [test_register.py-->line:83] - INFO:用例:手机号未注册,执行通过
2020-03-16 16:44:30,440 - [test_register.py-->line:83] - INFO:用例:密码错误,执行通过
2020-03-16 16:44:30,735 - [test_register.py-->line:83] - INFO:用例:手机号格式错误,执行通过
2020-03-16 16:44:31,174 - [test_register.py-->line:43] - ERROR:用例:注册成功-带注册名,执行未通过
2020-03-16 16:44:31,174 - [test_register.py-->line:44] - ERROR:0 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 39, in test_register
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2020-03-16 16:44:31,359 - [test_register.py-->line:43] - ERROR:用例:成功-不带用户名,执行未通过
2020-03-16 16:44:31,360 - [test_register.py-->line:44] - ERROR:0 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 39, in test_register
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2020-03-16 16:44:31,528 - [test_register.py-->line:49] - INFO:用例:不输入手机号,执行通过
2020-03-16 16:44:31,706 - [test_register.py-->line:49] - INFO:用例:手机号长度10位,执行通过
2020-03-16 16:44:31,853 - [test_register.py-->line:49] - INFO:用例:手机号长度12位,执行通过
2020-03-16 16:44:32,037 - [test_register.py-->line:49] - INFO:用例:手机号含有非法字符,执行通过
2020-03-16 16:44:32,238 - [test_register.py-->line:49] - INFO:用例:已注册过的手机号,执行通过
2020-03-16 16:44:32,431 - [test_register.py-->line:49] - INFO:用例:密码7位,执行通过
2020-03-16 16:44:32,643 - [test_register.py-->line:49] - INFO:用例:密码17位,执行通过
2020-03-16 16:44:32,929 - [test_register.py-->line:49] - INFO:用例:不输入密码,执行通过
2020-03-16 16:44:33,111 - [test_register.py-->line:49] - INFO:用例:注册名11位,执行通过
2020-03-16 16:44:33,295 - [test_register.py-->line:49] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-16 16:44:33,511 - [test_register.py-->line:43] - ERROR:用例:不输入类型,执行未通过
2020-03-16 16:44:33,511 - [test_register.py-->line:44] - ERROR:0 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 39, in test_register
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2020-03-16 16:46:07,524 - [test_register.py-->line:77] - ERROR:用例:登录成功,执行未通过
2020-03-16 16:46:07,525 - [test_register.py-->line:78] - ERROR:0 != 1001
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 1001
2020-03-16 16:46:07,977 - [test_register.py-->line:77] - ERROR:用例:手机号为空,执行未通过
2020-03-16 16:46:07,978 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-16 16:46:08,378 - [test_register.py-->line:77] - ERROR:用例:密码为空,执行未通过
2020-03-16 16:46:08,379 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-16 16:46:08,904 - [test_register.py-->line:83] - INFO:用例:手机号未注册,执行通过
2020-03-16 16:46:09,296 - [test_register.py-->line:83] - INFO:用例:密码错误,执行通过
2020-03-16 16:46:09,728 - [test_register.py-->line:83] - INFO:用例:手机号格式错误,执行通过
2020-03-16 16:46:43,122 - [test_register.py-->line:77] - ERROR:用例:登录成功,执行未通过
2020-03-16 16:46:43,122 - [test_register.py-->line:78] - ERROR:0 != 1001
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 1001
2020-03-16 16:46:43,278 - [test_register.py-->line:77] - ERROR:用例:手机号为空,执行未通过
2020-03-16 16:46:43,278 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-16 16:46:43,470 - [test_register.py-->line:77] - ERROR:用例:密码为空,执行未通过
2020-03-16 16:46:43,470 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-16 16:46:43,666 - [test_register.py-->line:83] - INFO:用例:手机号未注册,执行通过
2020-03-16 16:46:43,874 - [test_register.py-->line:83] - INFO:用例:密码错误,执行通过
2020-03-16 16:46:44,065 - [test_register.py-->line:83] - INFO:用例:手机号格式错误,执行通过
2020-03-16 16:46:44,377 - [test_register.py-->line:49] - INFO:用例:注册成功-带注册名,执行通过
2020-03-16 16:46:44,591 - [test_register.py-->line:49] - INFO:用例:成功-不带用户名,执行通过
2020-03-16 16:46:44,777 - [test_register.py-->line:49] - INFO:用例:不输入手机号,执行通过
2020-03-16 16:46:45,287 - [test_register.py-->line:49] - INFO:用例:手机号长度10位,执行通过
2020-03-16 16:46:45,467 - [test_register.py-->line:49] - INFO:用例:手机号长度12位,执行通过
2020-03-16 16:46:45,656 - [test_register.py-->line:49] - INFO:用例:手机号含有非法字符,执行通过
2020-03-16 16:46:45,863 - [test_register.py-->line:49] - INFO:用例:已注册过的手机号,执行通过
2020-03-16 16:46:46,052 - [test_register.py-->line:49] - INFO:用例:密码7位,执行通过
2020-03-16 16:46:46,238 - [test_register.py-->line:49] - INFO:用例:密码17位,执行通过
2020-03-16 16:46:46,660 - [test_register.py-->line:49] - INFO:用例:不输入密码,执行通过
2020-03-16 16:46:46,922 - [test_register.py-->line:49] - INFO:用例:注册名11位,执行通过
2020-03-16 16:46:47,075 - [test_register.py-->line:49] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-16 16:46:47,497 - [test_register.py-->line:49] - INFO:用例:不输入类型,执行通过
2020-03-16 18:13:54,457 - [test_register.py-->line:77] - ERROR:用例:登录成功,执行未通过
2020-03-16 18:13:54,458 - [test_register.py-->line:78] - ERROR:0 != 1001
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 1001
2020-03-16 18:13:54,590 - [test_register.py-->line:77] - ERROR:用例:手机号为空,执行未通过
2020-03-16 18:13:54,590 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-16 18:13:54,714 - [test_register.py-->line:77] - ERROR:用例:密码为空,执行未通过
2020-03-16 18:13:54,715 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-16 18:13:54,935 - [test_register.py-->line:83] - INFO:用例:手机号未注册,执行通过
2020-03-16 18:13:55,122 - [test_register.py-->line:83] - INFO:用例:密码错误,执行通过
2020-03-16 18:13:55,259 - [test_register.py-->line:83] - INFO:用例:手机号格式错误,执行通过
2020-03-16 18:13:55,560 - [test_register.py-->line:49] - INFO:用例:注册成功-带注册名,执行通过
2020-03-16 18:13:55,744 - [test_register.py-->line:49] - INFO:用例:成功-不带用户名,执行通过
2020-03-16 18:13:55,887 - [test_register.py-->line:49] - INFO:用例:不输入手机号,执行通过
2020-03-16 18:13:56,008 - [test_register.py-->line:49] - INFO:用例:手机号长度10位,执行通过
2020-03-16 18:13:56,117 - [test_register.py-->line:49] - INFO:用例:手机号长度12位,执行通过
2020-03-16 18:13:56,233 - [test_register.py-->line:49] - INFO:用例:手机号含有非法字符,执行通过
2020-03-16 18:13:56,417 - [test_register.py-->line:49] - INFO:用例:已注册过的手机号,执行通过
2020-03-16 18:13:56,531 - [test_register.py-->line:49] - INFO:用例:密码7位,执行通过
2020-03-16 18:13:56,675 - [test_register.py-->line:49] - INFO:用例:密码17位,执行通过
2020-03-16 18:13:56,822 - [test_register.py-->line:49] - INFO:用例:不输入密码,执行通过
2020-03-16 18:13:56,974 - [test_register.py-->line:49] - INFO:用例:注册名11位,执行通过
2020-03-16 18:13:57,119 - [test_register.py-->line:49] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-16 18:13:57,288 - [test_register.py-->line:49] - INFO:用例:不输入类型,执行通过
2020-03-16 18:17:01,222 - [test_register.py-->line:77] - ERROR:用例:登录成功,执行未通过
2020-03-16 18:17:01,222 - [test_register.py-->line:78] - ERROR:0 != 1001
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 1001
2020-03-16 18:17:01,366 - [test_register.py-->line:77] - ERROR:用例:手机号为空,执行未通过
2020-03-16 18:17:01,366 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-16 18:17:01,495 - [test_register.py-->line:77] - ERROR:用例:密码为空,执行未通过
2020-03-16 18:17:01,495 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-16 18:17:01,692 - [test_register.py-->line:83] - INFO:用例:手机号未注册,执行通过
2020-03-16 18:17:01,872 - [test_register.py-->line:83] - INFO:用例:密码错误,执行通过
2020-03-16 18:17:02,050 - [test_register.py-->line:83] - INFO:用例:手机号格式错误,执行通过
2020-03-16 18:17:02,304 - [test_register.py-->line:49] - INFO:用例:注册成功-带注册名,执行通过
2020-03-16 18:17:02,495 - [test_register.py-->line:49] - INFO:用例:成功-不带用户名,执行通过
2020-03-16 18:17:02,662 - [test_register.py-->line:49] - INFO:用例:不输入手机号,执行通过
2020-03-16 18:17:02,836 - [test_register.py-->line:49] - INFO:用例:手机号长度10位,执行通过
2020-03-16 18:17:02,977 - [test_register.py-->line:49] - INFO:用例:手机号长度12位,执行通过
2020-03-16 18:17:03,146 - [test_register.py-->line:49] - INFO:用例:手机号含有非法字符,执行通过
2020-03-16 18:17:03,327 - [test_register.py-->line:49] - INFO:用例:已注册过的手机号,执行通过
2020-03-16 18:17:03,443 - [test_register.py-->line:49] - INFO:用例:密码7位,执行通过
2020-03-16 18:17:03,560 - [test_register.py-->line:49] - INFO:用例:密码17位,执行通过
2020-03-16 18:17:03,673 - [test_register.py-->line:49] - INFO:用例:不输入密码,执行通过
2020-03-16 18:17:03,832 - [test_register.py-->line:49] - INFO:用例:注册名11位,执行通过
2020-03-16 18:17:03,954 - [test_register.py-->line:49] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-16 18:17:04,142 - [test_register.py-->line:49] - INFO:用例:不输入类型,执行通过
2020-03-19 14:48:43,373 - [test_recharge.py-->line:49] - INFO:用例:充值不成功-MemberId为空,执行通过
2020-03-19 14:48:43,672 - [test_register.py-->line:83] - INFO:用例:登录成功,执行通过
2020-03-19 14:48:43,836 - [test_register.py-->line:77] - ERROR:用例:手机号为空,执行未通过
2020-03-19 14:48:43,836 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-19 14:48:43,976 - [test_register.py-->line:77] - ERROR:用例:密码为空,执行未通过
2020-03-19 14:48:43,977 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-19 14:48:44,145 - [test_register.py-->line:83] - INFO:用例:手机号未注册,执行通过
2020-03-19 14:48:44,357 - [test_register.py-->line:83] - INFO:用例:密码错误,执行通过
2020-03-19 14:48:44,521 - [test_register.py-->line:83] - INFO:用例:手机号格式错误,执行通过
2020-03-19 14:48:44,729 - [test_register.py-->line:49] - INFO:用例:注册成功-带注册名,执行通过
2020-03-19 14:48:44,948 - [test_register.py-->line:49] - INFO:用例:成功-不带用户名,执行通过
2020-03-19 14:48:45,113 - [test_register.py-->line:49] - INFO:用例:不输入手机号,执行通过
2020-03-19 14:48:45,313 - [test_register.py-->line:49] - INFO:用例:手机号长度10位,执行通过
2020-03-19 14:48:45,453 - [test_register.py-->line:49] - INFO:用例:手机号长度12位,执行通过
2020-03-19 14:48:45,596 - [test_register.py-->line:49] - INFO:用例:手机号含有非法字符,执行通过
2020-03-19 14:48:45,791 - [test_register.py-->line:49] - INFO:用例:已注册过的手机号,执行通过
2020-03-19 14:48:46,091 - [test_register.py-->line:49] - INFO:用例:密码7位,执行通过
2020-03-19 14:48:46,251 - [test_register.py-->line:49] - INFO:用例:密码17位,执行通过
2020-03-19 14:48:46,418 - [test_register.py-->line:49] - INFO:用例:不输入密码,执行通过
2020-03-19 14:48:46,630 - [test_register.py-->line:49] - INFO:用例:注册名11位,执行通过
2020-03-19 14:48:46,863 - [test_register.py-->line:49] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-19 14:48:47,115 - [test_register.py-->line:49] - INFO:用例:不输入类型,执行通过
2020-03-19 15:44:18,474 - [test_register.py-->line:83] - INFO:用例:登录成功,执行通过
2020-03-19 15:44:18,792 - [test_register.py-->line:77] - ERROR:用例:手机号为空,执行未通过
2020-03-19 15:44:18,793 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-19 15:44:19,036 - [test_register.py-->line:77] - ERROR:用例:密码为空,执行未通过
2020-03-19 15:44:19,036 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-19 15:44:19,298 - [test_register.py-->line:83] - INFO:用例:手机号未注册,执行通过
2020-03-19 15:44:19,597 - [test_register.py-->line:83] - INFO:用例:密码错误,执行通过
2020-03-19 15:44:19,809 - [test_register.py-->line:83] - INFO:用例:手机号格式错误,执行通过
2020-03-19 15:44:20,083 - [test_register.py-->line:49] - INFO:用例:注册成功-带注册名,执行通过
2020-03-19 15:44:20,289 - [test_register.py-->line:49] - INFO:用例:成功-不带用户名,执行通过
2020-03-19 15:44:20,477 - [test_register.py-->line:49] - INFO:用例:不输入手机号,执行通过
2020-03-19 15:44:20,704 - [test_register.py-->line:49] - INFO:用例:手机号长度10位,执行通过
2020-03-19 15:44:20,911 - [test_register.py-->line:49] - INFO:用例:手机号长度12位,执行通过
2020-03-19 15:44:21,093 - [test_register.py-->line:49] - INFO:用例:手机号含有非法字符,执行通过
2020-03-19 15:44:21,300 - [test_register.py-->line:49] - INFO:用例:已注册过的手机号,执行通过
2020-03-19 15:44:21,483 - [test_register.py-->line:49] - INFO:用例:密码7位,执行通过
2020-03-19 15:44:21,681 - [test_register.py-->line:49] - INFO:用例:密码17位,执行通过
2020-03-19 15:44:21,897 - [test_register.py-->line:49] - INFO:用例:不输入密码,执行通过
2020-03-19 15:44:22,154 - [test_register.py-->line:49] - INFO:用例:注册名11位,执行通过
2020-03-19 15:44:22,359 - [test_register.py-->line:49] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-19 15:44:22,607 - [test_register.py-->line:49] - INFO:用例:不输入类型,执行通过
2020-03-19 15:45:55,152 - [test_register.py-->line:83] - INFO:用例:登录成功,执行通过
2020-03-19 15:45:55,367 - [test_register.py-->line:77] - ERROR:用例:手机号为空,执行未通过
2020-03-19 15:45:55,368 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-19 15:45:55,573 - [test_register.py-->line:77] - ERROR:用例:密码为空,执行未通过
2020-03-19 15:45:55,574 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-19 15:45:55,888 - [test_register.py-->line:83] - INFO:用例:手机号未注册,执行通过
2020-03-19 15:45:56,118 - [test_register.py-->line:83] - INFO:用例:密码错误,执行通过
2020-03-19 15:45:56,371 - [test_register.py-->line:83] - INFO:用例:手机号格式错误,执行通过
2020-03-19 15:45:56,665 - [test_register.py-->line:49] - INFO:用例:注册成功-带注册名,执行通过
2020-03-19 15:45:57,070 - [test_register.py-->line:49] - INFO:用例:成功-不带用户名,执行通过
2020-03-19 15:45:57,303 - [test_register.py-->line:49] - INFO:用例:不输入手机号,执行通过
2020-03-19 15:45:57,654 - [test_register.py-->line:49] - INFO:用例:手机号长度10位,执行通过
2020-03-19 15:45:57,956 - [test_register.py-->line:49] - INFO:用例:手机号长度12位,执行通过
2020-03-19 15:45:58,242 - [test_register.py-->line:49] - INFO:用例:手机号含有非法字符,执行通过
2020-03-19 15:45:58,502 - [test_register.py-->line:49] - INFO:用例:已注册过的手机号,执行通过
2020-03-19 15:45:59,087 - [test_register.py-->line:49] - INFO:用例:密码7位,执行通过
2020-03-19 15:45:59,503 - [test_register.py-->line:49] - INFO:用例:密码17位,执行通过
2020-03-19 15:45:59,708 - [test_register.py-->line:49] - INFO:用例:不输入密码,执行通过
2020-03-19 15:46:00,104 - [test_register.py-->line:49] - INFO:用例:注册名11位,执行通过
2020-03-19 15:46:00,618 - [test_register.py-->line:49] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-19 15:46:01,175 - [test_register.py-->line:49] - INFO:用例:不输入类型,执行通过
2020-03-19 15:50:31,357 - [test_recharge.py-->line:65] - INFO:用例:充值成功,执行通过
2020-03-19 15:50:32,175 - [test_recharge.py-->line:65] - INFO:用例:充值不成功-MemberId为空,执行通过
2020-03-19 15:50:33,106 - [test_recharge.py-->line:60] - ERROR:用例:充值不成功-Amount为空,执行未通过
2020-03-19 15:50:33,108 - [test_recharge.py-->line:61] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 56, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-19 15:50:33,711 - [test_recharge.py-->line:65] - INFO:用例:充值不成功-Amount为负值,执行通过
2020-03-19 15:50:34,341 - [test_recharge.py-->line:65] - INFO:用例:充值不成功-Amount大于500000,执行通过
2020-03-19 15:50:34,772 - [test_recharge.py-->line:65] - INFO:用例:充值不成功-Amount的小数位数多于2位,执行通过
2020-03-19 15:50:35,277 - [test_recharge.py-->line:65] - INFO:用例:充值成功-Amount的小数位数1位,执行通过
2020-03-19 15:50:35,857 - [test_recharge.py-->line:65] - INFO:用例:充值成功-Amount的小数位数2位,执行通过
2020-03-19 15:50:36,377 - [test_register.py-->line:83] - INFO:用例:登录成功,执行通过
2020-03-19 15:50:36,898 - [test_register.py-->line:77] - ERROR:用例:手机号为空,执行未通过
2020-03-19 15:50:36,898 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-19 15:50:37,264 - [test_register.py-->line:77] - ERROR:用例:密码为空,执行未通过
2020-03-19 15:50:37,265 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-19 15:50:37,881 - [test_register.py-->line:83] - INFO:用例:手机号未注册,执行通过
2020-03-19 15:50:38,542 - [test_register.py-->line:83] - INFO:用例:密码错误,执行通过
2020-03-19 15:50:39,191 - [test_register.py-->line:83] - INFO:用例:手机号格式错误,执行通过
2020-03-19 15:50:39,702 - [test_register.py-->line:49] - INFO:用例:注册成功-带注册名,执行通过
2020-03-19 15:50:40,284 - [test_register.py-->line:49] - INFO:用例:成功-不带用户名,执行通过
2020-03-19 15:50:40,882 - [test_register.py-->line:49] - INFO:用例:不输入手机号,执行通过
2020-03-19 15:50:41,279 - [test_register.py-->line:49] - INFO:用例:手机号长度10位,执行通过
2020-03-19 15:50:41,754 - [test_register.py-->line:49] - INFO:用例:手机号长度12位,执行通过
2020-03-19 15:50:42,387 - [test_register.py-->line:49] - INFO:用例:手机号含有非法字符,执行通过
2020-03-19 15:50:42,923 - [test_register.py-->line:49] - INFO:用例:已注册过的手机号,执行通过
2020-03-19 15:50:43,292 - [test_register.py-->line:49] - INFO:用例:密码7位,执行通过
2020-03-19 15:50:43,888 - [test_register.py-->line:49] - INFO:用例:密码17位,执行通过
2020-03-19 15:50:44,405 - [test_register.py-->line:49] - INFO:用例:不输入密码,执行通过
2020-03-19 15:50:45,143 - [test_register.py-->line:49] - INFO:用例:注册名11位,执行通过
2020-03-19 15:50:45,592 - [test_register.py-->line:49] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-19 15:50:46,159 - [test_register.py-->line:49] - INFO:用例:不输入类型,执行通过
2020-03-21 16:21:19,343 - [test_register.py-->line:83] - INFO:用例:登录成功,执行通过
2020-03-21 16:21:19,490 - [test_register.py-->line:77] - ERROR:用例:手机号为空,执行未通过
2020-03-21 16:21:19,490 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 16:21:19,620 - [test_register.py-->line:77] - ERROR:用例:密码为空,执行未通过
2020-03-21 16:21:19,620 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 16:21:19,810 - [test_register.py-->line:83] - INFO:用例:手机号未注册,执行通过
2020-03-21 16:21:19,972 - [test_register.py-->line:83] - INFO:用例:密码错误,执行通过
2020-03-21 16:21:20,095 - [test_register.py-->line:83] - INFO:用例:手机号格式错误,执行通过
2020-03-21 16:21:20,287 - [test_register.py-->line:49] - INFO:用例:注册成功-带注册名,执行通过
2020-03-21 16:21:20,475 - [test_register.py-->line:49] - INFO:用例:成功-不带用户名,执行通过
2020-03-21 16:21:20,647 - [test_register.py-->line:49] - INFO:用例:不输入手机号,执行通过
2020-03-21 16:21:20,810 - [test_register.py-->line:49] - INFO:用例:手机号长度10位,执行通过
2020-03-21 16:21:20,970 - [test_register.py-->line:49] - INFO:用例:手机号长度12位,执行通过
2020-03-21 16:21:21,107 - [test_register.py-->line:49] - INFO:用例:手机号含有非法字符,执行通过
2020-03-21 16:21:21,261 - [test_register.py-->line:49] - INFO:用例:已注册过的手机号,执行通过
2020-03-21 16:21:21,384 - [test_register.py-->line:49] - INFO:用例:密码7位,执行通过
2020-03-21 16:21:21,511 - [test_register.py-->line:49] - INFO:用例:密码17位,执行通过
2020-03-21 16:21:21,629 - [test_register.py-->line:49] - INFO:用例:不输入密码,执行通过
2020-03-21 16:21:21,752 - [test_register.py-->line:49] - INFO:用例:注册名11位,执行通过
2020-03-21 16:21:21,871 - [test_register.py-->line:49] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-21 16:21:22,038 - [test_register.py-->line:49] - INFO:用例:不输入类型,执行通过
2020-03-21 16:24:10,093 - [test_register.py-->line:83] - INFO:用例:登录成功,执行通过
2020-03-21 16:24:10,249 - [test_register.py-->line:77] - ERROR:用例:手机号为空,执行未通过
2020-03-21 16:24:10,249 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 16:24:10,406 - [test_register.py-->line:77] - ERROR:用例:密码为空,执行未通过
2020-03-21 16:24:10,406 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 16:24:10,561 - [test_register.py-->line:83] - INFO:用例:手机号未注册,执行通过
2020-03-21 16:24:10,705 - [test_register.py-->line:83] - INFO:用例:密码错误,执行通过
2020-03-21 16:24:10,827 - [test_register.py-->line:83] - INFO:用例:手机号格式错误,执行通过
2020-03-21 16:24:11,028 - [test_register.py-->line:49] - INFO:用例:注册成功-带注册名,执行通过
2020-03-21 16:24:11,198 - [test_register.py-->line:49] - INFO:用例:成功-不带用户名,执行通过
2020-03-21 16:24:11,336 - [test_register.py-->line:49] - INFO:用例:不输入手机号,执行通过
2020-03-21 16:24:11,464 - [test_register.py-->line:49] - INFO:用例:手机号长度10位,执行通过
2020-03-21 16:24:11,603 - [test_register.py-->line:49] - INFO:用例:手机号长度12位,执行通过
2020-03-21 16:24:11,715 - [test_register.py-->line:49] - INFO:用例:手机号含有非法字符,执行通过
2020-03-21 16:24:11,858 - [test_register.py-->line:49] - INFO:用例:已注册过的手机号,执行通过
2020-03-21 16:24:11,981 - [test_register.py-->line:49] - INFO:用例:密码7位,执行通过
2020-03-21 16:24:12,111 - [test_register.py-->line:49] - INFO:用例:密码17位,执行通过
2020-03-21 16:24:12,264 - [test_register.py-->line:49] - INFO:用例:不输入密码,执行通过
2020-03-21 16:24:12,378 - [test_register.py-->line:49] - INFO:用例:注册名11位,执行通过
2020-03-21 16:24:12,507 - [test_register.py-->line:49] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-21 16:24:12,660 - [test_register.py-->line:49] - INFO:用例:不输入类型,执行通过
2020-03-21 16:24:20,704 - [test_register.py-->line:83] - INFO:用例:登录成功,执行通过
2020-03-21 16:24:20,837 - [test_register.py-->line:77] - ERROR:用例:手机号为空,执行未通过
2020-03-21 16:24:20,837 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 16:24:20,961 - [test_register.py-->line:77] - ERROR:用例:密码为空,执行未通过
2020-03-21 16:24:20,961 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 16:24:21,096 - [test_register.py-->line:83] - INFO:用例:手机号未注册,执行通过
2020-03-21 16:24:21,247 - [test_register.py-->line:83] - INFO:用例:密码错误,执行通过
2020-03-21 16:24:21,372 - [test_register.py-->line:83] - INFO:用例:手机号格式错误,执行通过
2020-03-21 16:24:21,550 - [test_register.py-->line:49] - INFO:用例:注册成功-带注册名,执行通过
2020-03-21 16:24:21,685 - [test_register.py-->line:49] - INFO:用例:成功-不带用户名,执行通过
2020-03-21 16:24:21,809 - [test_register.py-->line:49] - INFO:用例:不输入手机号,执行通过
2020-03-21 16:24:21,918 - [test_register.py-->line:49] - INFO:用例:手机号长度10位,执行通过
2020-03-21 16:24:22,022 - [test_register.py-->line:49] - INFO:用例:手机号长度12位,执行通过
2020-03-21 16:24:22,138 - [test_register.py-->line:49] - INFO:用例:手机号含有非法字符,执行通过
2020-03-21 16:24:22,278 - [test_register.py-->line:49] - INFO:用例:已注册过的手机号,执行通过
2020-03-21 16:24:22,382 - [test_register.py-->line:49] - INFO:用例:密码7位,执行通过
2020-03-21 16:24:22,496 - [test_register.py-->line:49] - INFO:用例:密码17位,执行通过
2020-03-21 16:24:22,608 - [test_register.py-->line:49] - INFO:用例:不输入密码,执行通过
2020-03-21 16:24:22,715 - [test_register.py-->line:49] - INFO:用例:注册名11位,执行通过
2020-03-21 16:24:22,819 - [test_register.py-->line:49] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-21 16:24:22,963 - [test_register.py-->line:49] - INFO:用例:不输入类型,执行通过
2020-03-21 16:26:55,956 - [test_register.py-->line:83] - INFO:用例:登录成功,执行通过
2020-03-21 16:26:56,086 - [test_register.py-->line:77] - ERROR:用例:手机号为空,执行未通过
2020-03-21 16:26:56,086 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 16:26:56,216 - [test_register.py-->line:77] - ERROR:用例:密码为空,执行未通过
2020-03-21 16:26:56,216 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 16:26:56,397 - [test_register.py-->line:83] - INFO:用例:手机号未注册,执行通过
2020-03-21 16:26:56,575 - [test_register.py-->line:83] - INFO:用例:密码错误,执行通过
2020-03-21 16:26:56,744 - [test_register.py-->line:83] - INFO:用例:手机号格式错误,执行通过
2020-03-21 16:26:56,978 - [test_register.py-->line:49] - INFO:用例:注册成功-带注册名,执行通过
2020-03-21 16:26:57,165 - [test_register.py-->line:49] - INFO:用例:成功-不带用户名,执行通过
2020-03-21 16:26:57,284 - [test_register.py-->line:49] - INFO:用例:不输入手机号,执行通过
2020-03-21 16:26:57,483 - [test_register.py-->line:49] - INFO:用例:手机号长度10位,执行通过
2020-03-21 16:26:57,611 - [test_register.py-->line:49] - INFO:用例:手机号长度12位,执行通过
2020-03-21 16:26:57,750 - [test_register.py-->line:49] - INFO:用例:手机号含有非法字符,执行通过
2020-03-21 16:26:57,934 - [test_register.py-->line:49] - INFO:用例:已注册过的手机号,执行通过
2020-03-21 16:26:58,056 - [test_register.py-->line:49] - INFO:用例:密码7位,执行通过
2020-03-21 16:26:58,182 - [test_register.py-->line:49] - INFO:用例:密码17位,执行通过
2020-03-21 16:26:58,295 - [test_register.py-->line:49] - INFO:用例:不输入密码,执行通过
2020-03-21 16:26:58,550 - [test_register.py-->line:49] - INFO:用例:注册名11位,执行通过
2020-03-21 16:26:58,702 - [test_register.py-->line:49] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-21 16:26:58,844 - [test_register.py-->line:49] - INFO:用例:不输入类型,执行通过
2020-03-21 16:29:34,391 - [test_recharge.py-->line:76] - ERROR:用例:充值成功,执行未通过
2020-03-21 16:29:34,392 - [test_recharge.py-->line:77] - ERROR:10000 != Decimal('0.00')
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 73, in test_recharge
    self.assertEqual(data["amount"],end_money-start_money)
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 10000 != Decimal('0.00')
2020-03-21 16:29:34,520 - [test_recharge.py-->line:81] - INFO:用例:充值不成功-MemberId为空,执行通过
2020-03-21 16:29:34,637 - [test_recharge.py-->line:76] - ERROR:用例:充值不成功-Amount为空,执行未通过
2020-03-21 16:29:34,637 - [test_recharge.py-->line:77] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 69, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 16:29:34,766 - [test_recharge.py-->line:81] - INFO:用例:充值不成功-Amount为负值,执行通过
2020-03-21 16:29:35,018 - [test_recharge.py-->line:81] - INFO:用例:充值不成功-Amount大于500000,执行通过
2020-03-21 16:29:35,182 - [test_recharge.py-->line:81] - INFO:用例:充值不成功-Amount的小数位数多于2位,执行通过
2020-03-21 16:29:35,579 - [test_recharge.py-->line:76] - ERROR:用例:充值成功-Amount的小数位数1位,执行未通过
2020-03-21 16:29:35,579 - [test_recharge.py-->line:77] - ERROR:400000.1 != Decimal('0.00')
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 73, in test_recharge
    self.assertEqual(data["amount"],end_money-start_money)
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 400000.1 != Decimal('0.00')
2020-03-21 16:29:35,951 - [test_recharge.py-->line:76] - ERROR:用例:充值成功-Amount的小数位数2位,执行未通过
2020-03-21 16:29:35,951 - [test_recharge.py-->line:77] - ERROR:400000.09 != Decimal('0.00')
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 73, in test_recharge
    self.assertEqual(data["amount"],end_money-start_money)
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 400000.09 != Decimal('0.00')
2020-03-21 16:29:36,197 - [test_register.py-->line:83] - INFO:用例:登录成功,执行通过
2020-03-21 16:29:36,318 - [test_register.py-->line:77] - ERROR:用例:手机号为空,执行未通过
2020-03-21 16:29:36,318 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 16:29:36,460 - [test_register.py-->line:77] - ERROR:用例:密码为空,执行未通过
2020-03-21 16:29:36,461 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 16:29:36,635 - [test_register.py-->line:83] - INFO:用例:手机号未注册,执行通过
2020-03-21 16:29:36,878 - [test_register.py-->line:83] - INFO:用例:密码错误,执行通过
2020-03-21 16:29:37,063 - [test_register.py-->line:83] - INFO:用例:手机号格式错误,执行通过
2020-03-21 16:29:37,305 - [test_register.py-->line:49] - INFO:用例:注册成功-带注册名,执行通过
2020-03-21 16:29:37,481 - [test_register.py-->line:49] - INFO:用例:成功-不带用户名,执行通过
2020-03-21 16:29:37,704 - [test_register.py-->line:49] - INFO:用例:不输入手机号,执行通过
2020-03-21 16:29:37,868 - [test_register.py-->line:49] - INFO:用例:手机号长度10位,执行通过
2020-03-21 16:29:38,001 - [test_register.py-->line:49] - INFO:用例:手机号长度12位,执行通过
2020-03-21 16:29:38,151 - [test_register.py-->line:49] - INFO:用例:手机号含有非法字符,执行通过
2020-03-21 16:29:38,433 - [test_register.py-->line:49] - INFO:用例:已注册过的手机号,执行通过
2020-03-21 16:29:38,609 - [test_register.py-->line:49] - INFO:用例:密码7位,执行通过
2020-03-21 16:29:38,766 - [test_register.py-->line:49] - INFO:用例:密码17位,执行通过
2020-03-21 16:29:38,909 - [test_register.py-->line:49] - INFO:用例:不输入密码,执行通过
2020-03-21 16:29:39,047 - [test_register.py-->line:49] - INFO:用例:注册名11位,执行通过
2020-03-21 16:29:39,215 - [test_register.py-->line:49] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-21 16:29:39,429 - [test_register.py-->line:49] - INFO:用例:不输入类型,执行通过
2020-03-21 16:39:01,276 - [test_recharge.py-->line:81] - INFO:用例:充值不成功-MemberId为空,执行通过
2020-03-21 16:39:01,482 - [test_recharge.py-->line:76] - ERROR:用例:充值不成功-Amount为空,执行未通过
2020-03-21 16:39:01,484 - [test_recharge.py-->line:77] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 69, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 16:39:01,638 - [test_recharge.py-->line:81] - INFO:用例:充值不成功-Amount为负值,执行通过
2020-03-21 16:39:01,774 - [test_recharge.py-->line:81] - INFO:用例:充值不成功-Amount大于500000,执行通过
2020-03-21 16:39:01,979 - [test_recharge.py-->line:81] - INFO:用例:充值不成功-Amount的小数位数多于2位,执行通过
2020-03-21 16:39:02,297 - [test_register.py-->line:83] - INFO:用例:登录成功,执行通过
2020-03-21 16:39:02,537 - [test_register.py-->line:77] - ERROR:用例:手机号为空,执行未通过
2020-03-21 16:39:02,538 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 16:39:02,726 - [test_register.py-->line:77] - ERROR:用例:密码为空,执行未通过
2020-03-21 16:39:02,726 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 16:39:02,942 - [test_register.py-->line:83] - INFO:用例:手机号未注册,执行通过
2020-03-21 16:39:03,124 - [test_register.py-->line:83] - INFO:用例:密码错误,执行通过
2020-03-21 16:39:03,309 - [test_register.py-->line:83] - INFO:用例:手机号格式错误,执行通过
2020-03-21 16:39:03,652 - [test_register.py-->line:49] - INFO:用例:注册成功-带注册名,执行通过
2020-03-21 16:39:03,860 - [test_register.py-->line:49] - INFO:用例:成功-不带用户名,执行通过
2020-03-21 16:39:04,092 - [test_register.py-->line:49] - INFO:用例:不输入手机号,执行通过
2020-03-21 16:39:04,282 - [test_register.py-->line:49] - INFO:用例:手机号长度10位,执行通过
2020-03-21 16:39:04,432 - [test_register.py-->line:49] - INFO:用例:手机号长度12位,执行通过
2020-03-21 16:39:04,562 - [test_register.py-->line:49] - INFO:用例:手机号含有非法字符,执行通过
2020-03-21 16:39:04,768 - [test_register.py-->line:49] - INFO:用例:已注册过的手机号,执行通过
2020-03-21 16:39:04,907 - [test_register.py-->line:49] - INFO:用例:密码7位,执行通过
2020-03-21 16:39:05,047 - [test_register.py-->line:49] - INFO:用例:密码17位,执行通过
2020-03-21 16:39:05,302 - [test_register.py-->line:49] - INFO:用例:不输入密码,执行通过
2020-03-21 16:39:05,499 - [test_register.py-->line:49] - INFO:用例:注册名11位,执行通过
2020-03-21 16:39:05,645 - [test_register.py-->line:49] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-21 16:39:05,867 - [test_register.py-->line:49] - INFO:用例:不输入类型,执行通过
2020-03-21 16:40:11,149 - [test_recharge.py-->line:81] - INFO:用例:充值成功,执行通过
2020-03-21 16:40:11,308 - [test_recharge.py-->line:81] - INFO:用例:充值不成功-MemberId为空,执行通过
2020-03-21 16:40:11,540 - [test_recharge.py-->line:76] - ERROR:用例:充值不成功-Amount为空,执行未通过
2020-03-21 16:40:11,541 - [test_recharge.py-->line:77] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 69, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 16:40:11,718 - [test_recharge.py-->line:81] - INFO:用例:充值不成功-Amount为负值,执行通过
2020-03-21 16:40:11,936 - [test_recharge.py-->line:81] - INFO:用例:充值不成功-Amount大于500000,执行通过
2020-03-21 16:40:12,087 - [test_recharge.py-->line:81] - INFO:用例:充值不成功-Amount的小数位数多于2位,执行通过
2020-03-21 16:40:12,705 - [test_recharge.py-->line:76] - ERROR:用例:充值成功-Amount的小数位数1位,执行未通过
2020-03-21 16:40:12,705 - [test_recharge.py-->line:77] - ERROR:400000.1 != Decimal('400000.10')
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 73, in test_recharge
    self.assertEqual(data["amount"],end_money-start_money)
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 400000.1 != Decimal('400000.10')
2020-03-21 16:40:13,330 - [test_recharge.py-->line:76] - ERROR:用例:充值成功-Amount的小数位数2位,执行未通过
2020-03-21 16:40:13,330 - [test_recharge.py-->line:77] - ERROR:400000.09 != Decimal('400000.09')
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 73, in test_recharge
    self.assertEqual(data["amount"],end_money-start_money)
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 400000.09 != Decimal('400000.09')
2020-03-21 16:40:13,627 - [test_register.py-->line:83] - INFO:用例:登录成功,执行通过
2020-03-21 16:40:13,823 - [test_register.py-->line:77] - ERROR:用例:手机号为空,执行未通过
2020-03-21 16:40:13,823 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 16:40:14,024 - [test_register.py-->line:77] - ERROR:用例:密码为空,执行未通过
2020-03-21 16:40:14,024 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 16:40:14,190 - [test_register.py-->line:83] - INFO:用例:手机号未注册,执行通过
2020-03-21 16:40:14,368 - [test_register.py-->line:83] - INFO:用例:密码错误,执行通过
2020-03-21 16:40:14,512 - [test_register.py-->line:83] - INFO:用例:手机号格式错误,执行通过
2020-03-21 16:40:15,010 - [test_register.py-->line:49] - INFO:用例:注册成功-带注册名,执行通过
2020-03-21 16:40:15,261 - [test_register.py-->line:49] - INFO:用例:成功-不带用户名,执行通过
2020-03-21 16:40:15,416 - [test_register.py-->line:49] - INFO:用例:不输入手机号,执行通过
2020-03-21 16:40:15,686 - [test_register.py-->line:49] - INFO:用例:手机号长度10位,执行通过
2020-03-21 16:40:15,856 - [test_register.py-->line:49] - INFO:用例:手机号长度12位,执行通过
2020-03-21 16:40:16,109 - [test_register.py-->line:49] - INFO:用例:手机号含有非法字符,执行通过
2020-03-21 16:40:16,355 - [test_register.py-->line:49] - INFO:用例:已注册过的手机号,执行通过
2020-03-21 16:40:16,558 - [test_register.py-->line:49] - INFO:用例:密码7位,执行通过
2020-03-21 16:40:16,714 - [test_register.py-->line:49] - INFO:用例:密码17位,执行通过
2020-03-21 16:40:16,923 - [test_register.py-->line:49] - INFO:用例:不输入密码,执行通过
2020-03-21 16:40:17,229 - [test_register.py-->line:49] - INFO:用例:注册名11位,执行通过
2020-03-21 16:40:17,446 - [test_register.py-->line:49] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-21 16:40:17,622 - [test_register.py-->line:49] - INFO:用例:不输入类型,执行通过
2020-03-21 16:43:15,325 - [test_recharge.py-->line:82] - INFO:用例:充值成功,执行通过
2020-03-21 16:43:15,510 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-MemberId为空,执行通过
2020-03-21 16:43:15,645 - [test_recharge.py-->line:77] - ERROR:用例:充值不成功-Amount为空,执行未通过
2020-03-21 16:43:15,646 - [test_recharge.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 70, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 16:43:15,878 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount为负值,执行通过
2020-03-21 16:43:16,024 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount大于500000,执行通过
2020-03-21 16:43:16,177 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount的小数位数多于2位,执行通过
2020-03-21 16:43:17,027 - [test_recharge.py-->line:82] - INFO:用例:充值成功-Amount的小数位数1位,执行通过
2020-03-21 16:43:17,738 - [test_recharge.py-->line:82] - INFO:用例:充值成功-Amount的小数位数2位,执行通过
2020-03-21 16:43:17,985 - [test_register.py-->line:83] - INFO:用例:登录成功,执行通过
2020-03-21 16:43:18,176 - [test_register.py-->line:77] - ERROR:用例:手机号为空,执行未通过
2020-03-21 16:43:18,176 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 16:43:18,335 - [test_register.py-->line:77] - ERROR:用例:密码为空,执行未通过
2020-03-21 16:43:18,335 - [test_register.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 73, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 16:43:18,734 - [test_register.py-->line:83] - INFO:用例:手机号未注册,执行通过
2020-03-21 16:43:19,069 - [test_register.py-->line:83] - INFO:用例:密码错误,执行通过
2020-03-21 16:43:19,419 - [test_register.py-->line:83] - INFO:用例:手机号格式错误,执行通过
2020-03-21 16:43:20,073 - [test_register.py-->line:49] - INFO:用例:注册成功-带注册名,执行通过
2020-03-21 16:43:20,230 - [test_register.py-->line:49] - INFO:用例:成功-不带用户名,执行通过
2020-03-21 16:43:20,367 - [test_register.py-->line:49] - INFO:用例:不输入手机号,执行通过
2020-03-21 16:43:21,111 - [test_register.py-->line:49] - INFO:用例:手机号长度10位,执行通过
2020-03-21 16:43:21,551 - [test_register.py-->line:49] - INFO:用例:手机号长度12位,执行通过
2020-03-21 16:43:22,561 - [test_register.py-->line:49] - INFO:用例:手机号含有非法字符,执行通过
2020-03-21 16:43:22,759 - [test_register.py-->line:49] - INFO:用例:已注册过的手机号,执行通过
2020-03-21 16:43:23,282 - [test_register.py-->line:49] - INFO:用例:密码7位,执行通过
2020-03-21 16:43:23,597 - [test_register.py-->line:49] - INFO:用例:密码17位,执行通过
2020-03-21 16:43:23,759 - [test_register.py-->line:49] - INFO:用例:不输入密码,执行通过
2020-03-21 16:43:24,097 - [test_register.py-->line:49] - INFO:用例:注册名11位,执行通过
2020-03-21 16:43:24,278 - [test_register.py-->line:49] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-21 16:43:24,449 - [test_register.py-->line:49] - INFO:用例:不输入类型,执行通过
2020-03-21 16:47:33,923 - [test_recharge.py-->line:84] - INFO:用例:充值成功,执行通过
2020-03-21 16:47:34,071 - [test_recharge.py-->line:84] - INFO:用例:充值不成功-MemberId为空,执行通过
2020-03-21 16:47:34,337 - [test_recharge.py-->line:84] - INFO:用例:充值不成功-Amount为负值,执行通过
2020-03-21 16:47:34,501 - [test_recharge.py-->line:84] - INFO:用例:充值不成功-Amount大于500000,执行通过
2020-03-21 16:47:34,714 - [test_recharge.py-->line:84] - INFO:用例:充值不成功-Amount的小数位数多于2位,执行通过
2020-03-21 16:47:35,234 - [test_recharge.py-->line:84] - INFO:用例:充值成功-Amount的小数位数1位,执行通过
2020-03-21 16:47:35,772 - [test_recharge.py-->line:84] - INFO:用例:充值成功-Amount的小数位数2位,执行通过
2020-03-21 16:47:36,044 - [test_register.py-->line:87] - INFO:用例:登录成功,执行通过
2020-03-21 16:47:36,348 - [test_register.py-->line:87] - INFO:用例:手机号未注册,执行通过
2020-03-21 16:47:36,549 - [test_register.py-->line:87] - INFO:用例:密码错误,执行通过
2020-03-21 16:47:36,743 - [test_register.py-->line:87] - INFO:用例:手机号格式错误,执行通过
2020-03-21 16:47:37,031 - [test_register.py-->line:51] - INFO:用例:注册成功-带注册名,执行通过
2020-03-21 16:47:37,227 - [test_register.py-->line:51] - INFO:用例:成功-不带用户名,执行通过
2020-03-21 16:47:37,399 - [test_register.py-->line:51] - INFO:用例:不输入手机号,执行通过
2020-03-21 16:47:37,564 - [test_register.py-->line:51] - INFO:用例:手机号长度10位,执行通过
2020-03-21 16:47:37,838 - [test_register.py-->line:51] - INFO:用例:手机号长度12位,执行通过
2020-03-21 16:47:38,078 - [test_register.py-->line:51] - INFO:用例:手机号含有非法字符,执行通过
2020-03-21 16:47:38,340 - [test_register.py-->line:51] - INFO:用例:已注册过的手机号,执行通过
2020-03-21 16:47:38,482 - [test_register.py-->line:51] - INFO:用例:密码7位,执行通过
2020-03-21 16:47:38,615 - [test_register.py-->line:51] - INFO:用例:密码17位,执行通过
2020-03-21 16:47:38,816 - [test_register.py-->line:51] - INFO:用例:不输入密码,执行通过
2020-03-21 16:47:39,028 - [test_register.py-->line:51] - INFO:用例:注册名11位,执行通过
2020-03-21 16:47:39,217 - [test_register.py-->line:51] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-21 16:47:39,490 - [test_register.py-->line:51] - INFO:用例:不输入类型,执行通过
2020-03-21 16:49:19,320 - [test_recharge.py-->line:84] - INFO:用例:充值成功,执行通过
2020-03-21 16:49:19,616 - [test_recharge.py-->line:84] - INFO:用例:充值不成功-MemberId为空,执行通过
2020-03-21 16:49:19,802 - [test_recharge.py-->line:79] - ERROR:用例:充值不成功-Amount为空,执行未通过
2020-03-21 16:49:19,802 - [test_recharge.py-->line:80] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 70, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 16:49:19,938 - [test_recharge.py-->line:84] - INFO:用例:充值不成功-Amount为负值,执行通过
2020-03-21 16:49:20,168 - [test_recharge.py-->line:84] - INFO:用例:充值不成功-Amount大于500000,执行通过
2020-03-21 16:49:20,306 - [test_recharge.py-->line:84] - INFO:用例:充值不成功-Amount的小数位数多于2位,执行通过
2020-03-21 16:49:20,732 - [test_recharge.py-->line:84] - INFO:用例:充值成功-Amount的小数位数1位,执行通过
2020-03-21 16:49:21,432 - [test_recharge.py-->line:84] - INFO:用例:充值成功-Amount的小数位数2位,执行通过
2020-03-21 16:49:21,680 - [test_register.py-->line:87] - INFO:用例:登录成功,执行通过
2020-03-21 16:49:21,846 - [test_register.py-->line:81] - ERROR:用例:手机号为空,执行未通过
2020-03-21 16:49:21,846 - [test_register.py-->line:82] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 75, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 16:49:22,020 - [test_register.py-->line:81] - ERROR:用例:密码为空,执行未通过
2020-03-21 16:49:22,020 - [test_register.py-->line:82] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 75, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 16:49:22,429 - [test_register.py-->line:87] - INFO:用例:手机号未注册,执行通过
2020-03-21 16:49:22,886 - [test_register.py-->line:87] - INFO:用例:密码错误,执行通过
2020-03-21 16:49:23,309 - [test_register.py-->line:87] - INFO:用例:手机号格式错误,执行通过
2020-03-21 16:49:23,638 - [test_register.py-->line:51] - INFO:用例:注册成功-带注册名,执行通过
2020-03-21 16:49:23,821 - [test_register.py-->line:51] - INFO:用例:成功-不带用户名,执行通过
2020-03-21 16:49:23,971 - [test_register.py-->line:51] - INFO:用例:不输入手机号,执行通过
2020-03-21 16:49:24,193 - [test_register.py-->line:51] - INFO:用例:手机号长度10位,执行通过
2020-03-21 16:49:24,443 - [test_register.py-->line:51] - INFO:用例:手机号长度12位,执行通过
2020-03-21 16:49:24,694 - [test_register.py-->line:51] - INFO:用例:手机号含有非法字符,执行通过
2020-03-21 16:49:24,947 - [test_register.py-->line:51] - INFO:用例:已注册过的手机号,执行通过
2020-03-21 16:49:25,199 - [test_register.py-->line:51] - INFO:用例:密码7位,执行通过
2020-03-21 16:49:25,412 - [test_register.py-->line:51] - INFO:用例:密码17位,执行通过
2020-03-21 16:49:25,730 - [test_register.py-->line:51] - INFO:用例:不输入密码,执行通过
2020-03-21 16:49:25,948 - [test_register.py-->line:51] - INFO:用例:注册名11位,执行通过
2020-03-21 16:49:26,293 - [test_register.py-->line:51] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-21 16:49:26,622 - [test_register.py-->line:51] - INFO:用例:不输入类型,执行通过
2020-03-21 16:54:33,536 - [test_recharge.py-->line:82] - INFO:用例:充值成功,执行通过
2020-03-21 16:54:33,666 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-MemberId为空,执行通过
2020-03-21 16:54:33,814 - [test_recharge.py-->line:77] - ERROR:用例:充值不成功-Amount为空,执行未通过
2020-03-21 16:54:33,814 - [test_recharge.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 65, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 16:54:34,034 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount为负值,执行通过
2020-03-21 16:54:34,367 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount大于500000,执行通过
2020-03-21 16:54:34,877 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount的小数位数多于2位,执行通过
2020-03-21 16:54:35,518 - [test_recharge.py-->line:82] - INFO:用例:充值成功-Amount的小数位数1位,执行通过
2020-03-21 16:54:35,945 - [test_recharge.py-->line:82] - INFO:用例:充值成功-Amount的小数位数2位,执行通过
2020-03-21 16:54:36,207 - [test_register.py-->line:87] - INFO:用例:登录成功,执行通过
2020-03-21 16:54:36,352 - [test_register.py-->line:81] - ERROR:用例:手机号为空,执行未通过
2020-03-21 16:54:36,352 - [test_register.py-->line:82] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 75, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 16:54:36,486 - [test_register.py-->line:81] - ERROR:用例:密码为空,执行未通过
2020-03-21 16:54:36,487 - [test_register.py-->line:82] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 75, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 16:54:36,636 - [test_register.py-->line:87] - INFO:用例:手机号未注册,执行通过
2020-03-21 16:54:36,789 - [test_register.py-->line:87] - INFO:用例:密码错误,执行通过
2020-03-21 16:54:36,972 - [test_register.py-->line:87] - INFO:用例:手机号格式错误,执行通过
2020-03-21 16:54:37,251 - [test_register.py-->line:51] - INFO:用例:注册成功-带注册名,执行通过
2020-03-21 16:54:37,469 - [test_register.py-->line:51] - INFO:用例:成功-不带用户名,执行通过
2020-03-21 16:54:37,651 - [test_register.py-->line:51] - INFO:用例:不输入手机号,执行通过
2020-03-21 16:54:37,776 - [test_register.py-->line:51] - INFO:用例:手机号长度10位,执行通过
2020-03-21 16:54:38,074 - [test_register.py-->line:51] - INFO:用例:手机号长度12位,执行通过
2020-03-21 16:54:38,324 - [test_register.py-->line:51] - INFO:用例:手机号含有非法字符,执行通过
2020-03-21 16:54:38,511 - [test_register.py-->line:51] - INFO:用例:已注册过的手机号,执行通过
2020-03-21 16:54:38,656 - [test_register.py-->line:51] - INFO:用例:密码7位,执行通过
2020-03-21 16:54:38,860 - [test_register.py-->line:51] - INFO:用例:密码17位,执行通过
2020-03-21 16:54:39,011 - [test_register.py-->line:51] - INFO:用例:不输入密码,执行通过
2020-03-21 16:54:39,205 - [test_register.py-->line:51] - INFO:用例:注册名11位,执行通过
2020-03-21 16:54:39,393 - [test_register.py-->line:51] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-21 16:54:39,561 - [test_register.py-->line:51] - INFO:用例:不输入类型,执行通过
2020-03-21 22:55:38,206 - [test_recharge.py-->line:82] - INFO:用例:充值成功,执行通过
2020-03-21 22:55:38,410 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-MemberId为空,执行通过
2020-03-21 22:55:38,669 - [test_recharge.py-->line:77] - ERROR:用例:充值不成功-Amount为空,执行未通过
2020-03-21 22:55:38,669 - [test_recharge.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 65, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 22:55:38,874 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount为负值,执行通过
2020-03-21 22:55:39,123 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount大于500000,执行通过
2020-03-21 22:55:39,283 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount的小数位数多于2位,执行通过
2020-03-21 22:55:39,871 - [test_recharge.py-->line:82] - INFO:用例:充值成功-Amount的小数位数1位,执行通过
2020-03-21 22:55:40,283 - [test_recharge.py-->line:82] - INFO:用例:充值成功-Amount的小数位数2位,执行通过
2020-03-21 23:11:18,277 - [test_recharge.py-->line:82] - INFO:用例:充值成功,执行通过
2020-03-21 23:11:18,427 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-MemberId为空,执行通过
2020-03-21 23:11:18,581 - [test_recharge.py-->line:77] - ERROR:用例:充值不成功-Amount为空,执行未通过
2020-03-21 23:11:18,581 - [test_recharge.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 65, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 23:11:18,725 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount为负值,执行通过
2020-03-21 23:11:18,888 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount大于500000,执行通过
2020-03-21 23:11:19,061 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount的小数位数多于2位,执行通过
2020-03-21 23:11:19,396 - [test_recharge.py-->line:82] - INFO:用例:充值成功-Amount的小数位数1位,执行通过
2020-03-21 23:11:19,759 - [test_recharge.py-->line:82] - INFO:用例:充值成功-Amount的小数位数2位,执行通过
2020-03-21 23:11:20,000 - [test_register.py-->line:98] - INFO:用例:登录成功,执行通过
2020-03-21 23:11:20,166 - [test_register.py-->line:92] - ERROR:用例:手机号为空,执行未通过
2020-03-21 23:11:20,166 - [test_register.py-->line:93] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 86, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 23:11:20,321 - [test_register.py-->line:92] - ERROR:用例:密码为空,执行未通过
2020-03-21 23:11:20,322 - [test_register.py-->line:93] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 86, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 23:11:20,484 - [test_register.py-->line:98] - INFO:用例:手机号未注册,执行通过
2020-03-21 23:11:20,653 - [test_register.py-->line:98] - INFO:用例:密码错误,执行通过
2020-03-21 23:11:20,792 - [test_register.py-->line:98] - INFO:用例:手机号格式错误,执行通过
2020-03-21 23:11:21,189 - [test_register.py-->line:50] - ERROR:用例:注册成功-带注册名,执行未通过
2020-03-21 23:11:21,189 - [test_register.py-->line:51] - ERROR:1 != [{'id': 7800466, 'reg_name': '34254sdfs',[170 chars]21)}]
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 45, in test_register
    self.assertEqual(1,count)
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != [{'id': 7800466, 'reg_name': '34254sdfs',[170 chars]21)}]
2020-03-21 23:11:21,546 - [test_register.py-->line:50] - ERROR:用例:成功-不带用户名,执行未通过
2020-03-21 23:11:21,546 - [test_register.py-->line:51] - ERROR:1 != [{'id': 7800467, 'reg_name': '小柠檬', 'pwd'[164 chars]21)}]
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 45, in test_register
    self.assertEqual(1,count)
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != [{'id': 7800467, 'reg_name': '小柠檬', 'pwd'[164 chars]21)}]
2020-03-21 23:11:21,778 - [test_register.py-->line:56] - INFO:用例:不输入手机号,执行通过
2020-03-21 23:11:22,006 - [test_register.py-->line:56] - INFO:用例:手机号长度10位,执行通过
2020-03-21 23:11:22,254 - [test_register.py-->line:56] - INFO:用例:手机号长度12位,执行通过
2020-03-21 23:11:22,504 - [test_register.py-->line:56] - INFO:用例:手机号含有非法字符,执行通过
2020-03-21 23:11:22,754 - [test_register.py-->line:56] - INFO:用例:已注册过的手机号,执行通过
2020-03-21 23:11:22,977 - [test_register.py-->line:56] - INFO:用例:密码7位,执行通过
2020-03-21 23:11:23,237 - [test_register.py-->line:56] - INFO:用例:密码17位,执行通过
2020-03-21 23:11:23,481 - [test_register.py-->line:56] - INFO:用例:不输入密码,执行通过
2020-03-21 23:11:23,720 - [test_register.py-->line:56] - INFO:用例:注册名11位,执行通过
2020-03-21 23:11:23,943 - [test_register.py-->line:56] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-21 23:11:24,295 - [test_register.py-->line:50] - ERROR:用例:不输入类型,执行未通过
2020-03-21 23:11:24,295 - [test_register.py-->line:51] - ERROR:1 != [{'id': 7800468, 'reg_name': '小柠檬', 'pwd'[164 chars]24)}]
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 45, in test_register
    self.assertEqual(1,count)
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != [{'id': 7800468, 'reg_name': '小柠檬', 'pwd'[164 chars]24)}]
2020-03-21 23:13:42,861 - [test_recharge.py-->line:82] - INFO:用例:充值成功,执行通过
2020-03-21 23:13:42,975 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-MemberId为空,执行通过
2020-03-21 23:13:43,092 - [test_recharge.py-->line:77] - ERROR:用例:充值不成功-Amount为空,执行未通过
2020-03-21 23:13:43,093 - [test_recharge.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 65, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 23:13:43,215 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount为负值,执行通过
2020-03-21 23:13:43,334 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount大于500000,执行通过
2020-03-21 23:13:43,475 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount的小数位数多于2位,执行通过
2020-03-21 23:13:43,882 - [test_recharge.py-->line:82] - INFO:用例:充值成功-Amount的小数位数1位,执行通过
2020-03-21 23:13:44,218 - [test_recharge.py-->line:82] - INFO:用例:充值成功-Amount的小数位数2位,执行通过
2020-03-21 23:13:44,430 - [test_register.py-->line:98] - INFO:用例:登录成功,执行通过
2020-03-21 23:13:44,557 - [test_register.py-->line:92] - ERROR:用例:手机号为空,执行未通过
2020-03-21 23:13:44,558 - [test_register.py-->line:93] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 86, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 23:13:44,714 - [test_register.py-->line:92] - ERROR:用例:密码为空,执行未通过
2020-03-21 23:13:44,714 - [test_register.py-->line:93] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 86, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 23:13:44,871 - [test_register.py-->line:98] - INFO:用例:手机号未注册,执行通过
2020-03-21 23:13:45,024 - [test_register.py-->line:98] - INFO:用例:密码错误,执行通过
2020-03-21 23:13:45,165 - [test_register.py-->line:98] - INFO:用例:手机号格式错误,执行通过
2020-03-21 23:16:01,753 - [test_recharge.py-->line:82] - INFO:用例:充值成功,执行通过
2020-03-21 23:16:01,886 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-MemberId为空,执行通过
2020-03-21 23:16:02,031 - [test_recharge.py-->line:77] - ERROR:用例:充值不成功-Amount为空,执行未通过
2020-03-21 23:16:02,031 - [test_recharge.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 65, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 23:16:02,186 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount为负值,执行通过
2020-03-21 23:16:02,326 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount大于500000,执行通过
2020-03-21 23:16:02,494 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount的小数位数多于2位,执行通过
2020-03-21 23:16:02,811 - [test_recharge.py-->line:82] - INFO:用例:充值成功-Amount的小数位数1位,执行通过
2020-03-21 23:16:03,166 - [test_recharge.py-->line:82] - INFO:用例:充值成功-Amount的小数位数2位,执行通过
2020-03-21 23:16:03,369 - [test_register.py-->line:98] - INFO:用例:登录成功,执行通过
2020-03-21 23:16:03,505 - [test_register.py-->line:92] - ERROR:用例:手机号为空,执行未通过
2020-03-21 23:16:03,505 - [test_register.py-->line:93] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 86, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 23:16:03,649 - [test_register.py-->line:92] - ERROR:用例:密码为空,执行未通过
2020-03-21 23:16:03,649 - [test_register.py-->line:93] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 86, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 23:16:03,798 - [test_register.py-->line:98] - INFO:用例:手机号未注册,执行通过
2020-03-21 23:16:03,949 - [test_register.py-->line:98] - INFO:用例:密码错误,执行通过
2020-03-21 23:16:04,076 - [test_register.py-->line:98] - INFO:用例:手机号格式错误,执行通过
2020-03-21 23:16:16,225 - [test_recharge.py-->line:82] - INFO:用例:充值成功,执行通过
2020-03-21 23:16:16,576 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-MemberId为空,执行通过
2020-03-21 23:16:16,973 - [test_recharge.py-->line:77] - ERROR:用例:充值不成功-Amount为空,执行未通过
2020-03-21 23:16:16,973 - [test_recharge.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 65, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 23:16:17,408 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount为负值,执行通过
2020-03-21 23:16:17,775 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount大于500000,执行通过
2020-03-21 23:16:18,148 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount的小数位数多于2位,执行通过
2020-03-21 23:16:18,757 - [test_recharge.py-->line:82] - INFO:用例:充值成功-Amount的小数位数1位,执行通过
2020-03-21 23:16:19,370 - [test_recharge.py-->line:82] - INFO:用例:充值成功-Amount的小数位数2位,执行通过
2020-03-21 23:16:19,788 - [test_register.py-->line:98] - INFO:用例:登录成功,执行通过
2020-03-21 23:16:20,156 - [test_register.py-->line:92] - ERROR:用例:手机号为空,执行未通过
2020-03-21 23:16:20,157 - [test_register.py-->line:93] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 86, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 23:16:20,601 - [test_register.py-->line:92] - ERROR:用例:密码为空,执行未通过
2020-03-21 23:16:20,601 - [test_register.py-->line:93] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 86, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 23:16:21,012 - [test_register.py-->line:98] - INFO:用例:手机号未注册,执行通过
2020-03-21 23:16:21,402 - [test_register.py-->line:98] - INFO:用例:密码错误,执行通过
2020-03-21 23:16:21,792 - [test_register.py-->line:98] - INFO:用例:手机号格式错误,执行通过
2020-03-21 23:19:09,461 - [test_recharge.py-->line:82] - INFO:用例:充值成功,执行通过
2020-03-21 23:19:09,840 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-MemberId为空,执行通过
2020-03-21 23:19:10,222 - [test_recharge.py-->line:77] - ERROR:用例:充值不成功-Amount为空,执行未通过
2020-03-21 23:19:10,223 - [test_recharge.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 65, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 23:19:10,627 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount为负值,执行通过
2020-03-21 23:19:10,967 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount大于500000,执行通过
2020-03-21 23:19:11,322 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount的小数位数多于2位,执行通过
2020-03-21 23:19:11,878 - [test_recharge.py-->line:82] - INFO:用例:充值成功-Amount的小数位数1位,执行通过
2020-03-21 23:19:12,410 - [test_recharge.py-->line:82] - INFO:用例:充值成功-Amount的小数位数2位,执行通过
2020-03-21 23:19:12,845 - [test_register.py-->line:98] - INFO:用例:登录成功,执行通过
2020-03-21 23:19:13,190 - [test_register.py-->line:92] - ERROR:用例:手机号为空,执行未通过
2020-03-21 23:19:13,191 - [test_register.py-->line:93] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 86, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 23:19:13,567 - [test_register.py-->line:92] - ERROR:用例:密码为空,执行未通过
2020-03-21 23:19:13,568 - [test_register.py-->line:93] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 86, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 23:19:13,951 - [test_register.py-->line:98] - INFO:用例:手机号未注册,执行通过
2020-03-21 23:19:14,327 - [test_register.py-->line:98] - INFO:用例:密码错误,执行通过
2020-03-21 23:19:14,699 - [test_register.py-->line:98] - INFO:用例:手机号格式错误,执行通过
2020-03-21 23:31:44,261 - [test_recharge.py-->line:82] - INFO:用例:充值成功,执行通过
2020-03-21 23:31:44,392 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-MemberId为空,执行通过
2020-03-21 23:31:44,552 - [test_recharge.py-->line:77] - ERROR:用例:充值不成功-Amount为空,执行未通过
2020-03-21 23:31:44,553 - [test_recharge.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 65, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 23:31:44,732 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount为负值,执行通过
2020-03-21 23:31:44,864 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount大于500000,执行通过
2020-03-21 23:31:45,060 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount的小数位数多于2位,执行通过
2020-03-21 23:31:45,485 - [test_recharge.py-->line:82] - INFO:用例:充值成功-Amount的小数位数1位,执行通过
2020-03-21 23:31:45,856 - [test_recharge.py-->line:82] - INFO:用例:充值成功-Amount的小数位数2位,执行通过
2020-03-21 23:31:46,094 - [test_register.py-->line:97] - INFO:用例:登录成功,执行通过
2020-03-21 23:31:46,241 - [test_register.py-->line:91] - ERROR:用例:手机号为空,执行未通过
2020-03-21 23:31:46,241 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 23:31:46,367 - [test_register.py-->line:91] - ERROR:用例:密码为空,执行未通过
2020-03-21 23:31:46,367 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-21 23:31:46,517 - [test_register.py-->line:97] - INFO:用例:手机号未注册,执行通过
2020-03-21 23:31:46,709 - [test_register.py-->line:97] - INFO:用例:密码错误,执行通过
2020-03-21 23:31:46,841 - [test_register.py-->line:97] - INFO:用例:手机号格式错误,执行通过
2020-03-21 23:31:47,238 - [test_register.py-->line:56] - INFO:用例:注册成功-带注册名,执行通过
2020-03-21 23:31:47,623 - [test_register.py-->line:56] - INFO:用例:成功-不带用户名,执行通过
2020-03-21 23:31:47,894 - [test_register.py-->line:56] - INFO:用例:不输入手机号,执行通过
2020-03-21 23:31:48,110 - [test_register.py-->line:56] - INFO:用例:手机号长度10位,执行通过
2020-03-21 23:31:48,329 - [test_register.py-->line:56] - INFO:用例:手机号长度12位,执行通过
2020-03-21 23:31:48,592 - [test_register.py-->line:56] - INFO:用例:手机号含有非法字符,执行通过
2020-03-21 23:31:48,869 - [test_register.py-->line:56] - INFO:用例:已注册过的手机号,执行通过
2020-03-21 23:31:49,094 - [test_register.py-->line:56] - INFO:用例:密码7位,执行通过
2020-03-21 23:31:49,340 - [test_register.py-->line:56] - INFO:用例:密码17位,执行通过
2020-03-21 23:31:49,568 - [test_register.py-->line:56] - INFO:用例:不输入密码,执行通过
2020-03-21 23:31:49,819 - [test_register.py-->line:56] - INFO:用例:注册名11位,执行通过
2020-03-21 23:31:50,080 - [test_register.py-->line:56] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-21 23:31:50,560 - [test_register.py-->line:56] - INFO:用例:不输入类型,执行通过
2020-03-22 16:44:04,777 - [test_recharge.py-->line:82] - INFO:用例:充值成功,执行通过
2020-03-22 16:44:04,909 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-MemberId为空,执行通过
2020-03-22 16:44:05,044 - [test_recharge.py-->line:77] - ERROR:用例:充值不成功-Amount为空,执行未通过
2020-03-22 16:44:05,044 - [test_recharge.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 65, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-22 16:44:05,200 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount为负值,执行通过
2020-03-22 16:44:05,404 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount大于500000,执行通过
2020-03-22 16:44:05,628 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount的小数位数多于2位,执行通过
2020-03-22 16:44:05,965 - [test_recharge.py-->line:82] - INFO:用例:充值成功-Amount的小数位数1位,执行通过
2020-03-22 16:44:06,298 - [test_recharge.py-->line:82] - INFO:用例:充值成功-Amount的小数位数2位,执行通过
2020-03-22 16:44:06,548 - [test_register.py-->line:97] - INFO:用例:登录成功,执行通过
2020-03-22 16:44:06,695 - [test_register.py-->line:91] - ERROR:用例:手机号为空,执行未通过
2020-03-22 16:44:06,695 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-22 16:44:06,833 - [test_register.py-->line:91] - ERROR:用例:密码为空,执行未通过
2020-03-22 16:44:06,834 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-22 16:44:07,007 - [test_register.py-->line:97] - INFO:用例:手机号未注册,执行通过
2020-03-22 16:44:07,165 - [test_register.py-->line:97] - INFO:用例:密码错误,执行通过
2020-03-22 16:44:07,309 - [test_register.py-->line:97] - INFO:用例:手机号格式错误,执行通过
2020-03-22 16:44:07,711 - [test_register.py-->line:56] - INFO:用例:注册成功-带注册名,执行通过
2020-03-22 16:44:08,075 - [test_register.py-->line:56] - INFO:用例:成功-不带用户名,执行通过
2020-03-22 16:44:08,320 - [test_register.py-->line:56] - INFO:用例:不输入手机号,执行通过
2020-03-22 16:44:08,556 - [test_register.py-->line:56] - INFO:用例:手机号长度10位,执行通过
2020-03-22 16:44:08,790 - [test_register.py-->line:56] - INFO:用例:手机号长度12位,执行通过
2020-03-22 16:44:09,016 - [test_register.py-->line:56] - INFO:用例:手机号含有非法字符,执行通过
2020-03-22 16:44:09,268 - [test_register.py-->line:56] - INFO:用例:已注册过的手机号,执行通过
2020-03-22 16:44:09,550 - [test_register.py-->line:56] - INFO:用例:密码7位,执行通过
2020-03-22 16:44:09,850 - [test_register.py-->line:56] - INFO:用例:密码17位,执行通过
2020-03-22 16:44:10,084 - [test_register.py-->line:56] - INFO:用例:不输入密码,执行通过
2020-03-22 16:44:10,315 - [test_register.py-->line:56] - INFO:用例:注册名11位,执行通过
2020-03-22 16:44:10,562 - [test_register.py-->line:56] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-22 16:44:10,933 - [test_register.py-->line:56] - INFO:用例:不输入类型,执行通过
2020-03-22 16:46:42,828 - [test_recharge.py-->line:82] - INFO:用例:充值成功,执行通过
2020-03-22 16:46:42,988 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-MemberId为空,执行通过
2020-03-22 16:46:43,184 - [test_recharge.py-->line:77] - ERROR:用例:充值不成功-Amount为空,执行未通过
2020-03-22 16:46:43,185 - [test_recharge.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 65, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-22 16:46:43,323 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount为负值,执行通过
2020-03-22 16:46:43,515 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount大于500000,执行通过
2020-03-22 16:46:43,660 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount的小数位数多于2位,执行通过
2020-03-22 16:46:44,228 - [test_recharge.py-->line:82] - INFO:用例:充值成功-Amount的小数位数1位,执行通过
2020-03-22 16:46:44,560 - [test_recharge.py-->line:82] - INFO:用例:充值成功-Amount的小数位数2位,执行通过
2020-03-22 16:46:44,770 - [test_register.py-->line:97] - INFO:用例:登录成功,执行通过
2020-03-22 16:46:44,960 - [test_register.py-->line:91] - ERROR:用例:手机号为空,执行未通过
2020-03-22 16:46:44,961 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-22 16:46:45,125 - [test_register.py-->line:91] - ERROR:用例:密码为空,执行未通过
2020-03-22 16:46:45,125 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-22 16:46:45,335 - [test_register.py-->line:97] - INFO:用例:手机号未注册,执行通过
2020-03-22 16:46:45,510 - [test_register.py-->line:97] - INFO:用例:密码错误,执行通过
2020-03-22 16:46:45,655 - [test_register.py-->line:97] - INFO:用例:手机号格式错误,执行通过
2020-03-22 16:46:46,085 - [test_register.py-->line:56] - INFO:用例:注册成功-带注册名,执行通过
2020-03-22 16:46:46,491 - [test_register.py-->line:56] - INFO:用例:成功-不带用户名,执行通过
2020-03-22 16:46:46,748 - [test_register.py-->line:56] - INFO:用例:不输入手机号,执行通过
2020-03-22 16:46:46,984 - [test_register.py-->line:56] - INFO:用例:手机号长度10位,执行通过
2020-03-22 16:46:47,211 - [test_register.py-->line:56] - INFO:用例:手机号长度12位,执行通过
2020-03-22 16:46:47,489 - [test_register.py-->line:56] - INFO:用例:手机号含有非法字符,执行通过
2020-03-22 16:46:47,758 - [test_register.py-->line:56] - INFO:用例:已注册过的手机号,执行通过
2020-03-22 16:46:47,992 - [test_register.py-->line:56] - INFO:用例:密码7位,执行通过
2020-03-22 16:46:48,233 - [test_register.py-->line:56] - INFO:用例:密码17位,执行通过
2020-03-22 16:46:48,488 - [test_register.py-->line:56] - INFO:用例:不输入密码,执行通过
2020-03-22 16:46:48,776 - [test_register.py-->line:56] - INFO:用例:注册名11位,执行通过
2020-03-22 16:46:49,007 - [test_register.py-->line:56] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-22 16:46:49,378 - [test_register.py-->line:56] - INFO:用例:不输入类型,执行通过
2020-03-22 16:48:14,236 - [test_recharge.py-->line:82] - INFO:用例:充值成功,执行通过
2020-03-22 16:48:14,616 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-MemberId为空,执行通过
2020-03-22 16:48:15,060 - [test_recharge.py-->line:77] - ERROR:用例:充值不成功-Amount为空,执行未通过
2020-03-22 16:48:15,061 - [test_recharge.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 65, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-22 16:48:15,529 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount为负值,执行通过
2020-03-22 16:48:15,957 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount大于500000,执行通过
2020-03-22 16:48:16,347 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount的小数位数多于2位,执行通过
2020-03-22 16:48:16,952 - [test_recharge.py-->line:82] - INFO:用例:充值成功-Amount的小数位数1位,执行通过
2020-03-22 16:48:17,546 - [test_recharge.py-->line:82] - INFO:用例:充值成功-Amount的小数位数2位,执行通过
2020-03-22 16:48:17,981 - [test_register.py-->line:97] - INFO:用例:登录成功,执行通过
2020-03-22 16:48:18,394 - [test_register.py-->line:91] - ERROR:用例:手机号为空,执行未通过
2020-03-22 16:48:18,395 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-22 16:48:18,773 - [test_register.py-->line:91] - ERROR:用例:密码为空,执行未通过
2020-03-22 16:48:18,775 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-22 16:48:19,219 - [test_register.py-->line:97] - INFO:用例:手机号未注册,执行通过
2020-03-22 16:48:19,621 - [test_register.py-->line:97] - INFO:用例:密码错误,执行通过
2020-03-22 16:48:20,007 - [test_register.py-->line:97] - INFO:用例:手机号格式错误,执行通过
2020-03-22 16:48:20,720 - [test_register.py-->line:56] - INFO:用例:注册成功-带注册名,执行通过
2020-03-22 16:48:21,449 - [test_register.py-->line:56] - INFO:用例:成功-不带用户名,执行通过
2020-03-22 16:48:22,245 - [test_register.py-->line:56] - INFO:用例:不输入手机号,执行通过
2020-03-22 16:48:22,807 - [test_register.py-->line:56] - INFO:用例:手机号长度10位,执行通过
2020-03-22 16:48:23,318 - [test_register.py-->line:56] - INFO:用例:手机号长度12位,执行通过
2020-03-22 16:48:23,871 - [test_register.py-->line:56] - INFO:用例:手机号含有非法字符,执行通过
2020-03-22 16:48:24,443 - [test_register.py-->line:56] - INFO:用例:已注册过的手机号,执行通过
2020-03-22 16:48:24,979 - [test_register.py-->line:56] - INFO:用例:密码7位,执行通过
2020-03-22 16:48:25,508 - [test_register.py-->line:56] - INFO:用例:密码17位,执行通过
2020-03-22 16:48:26,066 - [test_register.py-->line:56] - INFO:用例:不输入密码,执行通过
2020-03-22 16:48:26,586 - [test_register.py-->line:56] - INFO:用例:注册名11位,执行通过
2020-03-22 16:48:27,114 - [test_register.py-->line:56] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-22 16:48:27,753 - [test_register.py-->line:56] - INFO:用例:不输入类型,执行通过
2020-03-22 16:50:11,196 - [test_recharge.py-->line:82] - INFO:用例:充值成功,执行通过
2020-03-22 16:50:11,346 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-MemberId为空,执行通过
2020-03-22 16:50:11,490 - [test_recharge.py-->line:77] - ERROR:用例:充值不成功-Amount为空,执行未通过
2020-03-22 16:50:11,490 - [test_recharge.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 65, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-22 16:50:11,629 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount为负值,执行通过
2020-03-22 16:50:11,793 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount大于500000,执行通过
2020-03-22 16:50:11,945 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount的小数位数多于2位,执行通过
2020-03-22 16:50:12,314 - [test_recharge.py-->line:82] - INFO:用例:充值成功-Amount的小数位数1位,执行通过
2020-03-22 16:50:12,681 - [test_recharge.py-->line:82] - INFO:用例:充值成功-Amount的小数位数2位,执行通过
2020-03-22 16:50:12,905 - [test_register.py-->line:97] - INFO:用例:登录成功,执行通过
2020-03-22 16:50:13,060 - [test_register.py-->line:91] - ERROR:用例:手机号为空,执行未通过
2020-03-22 16:50:13,060 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-22 16:50:13,242 - [test_register.py-->line:91] - ERROR:用例:密码为空,执行未通过
2020-03-22 16:50:13,242 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-22 16:50:13,429 - [test_register.py-->line:97] - INFO:用例:手机号未注册,执行通过
2020-03-22 16:50:13,644 - [test_register.py-->line:97] - INFO:用例:密码错误,执行通过
2020-03-22 16:50:13,833 - [test_register.py-->line:97] - INFO:用例:手机号格式错误,执行通过
2020-03-22 16:50:14,230 - [test_register.py-->line:56] - INFO:用例:注册成功-带注册名,执行通过
2020-03-22 16:50:14,628 - [test_register.py-->line:56] - INFO:用例:成功-不带用户名,执行通过
2020-03-22 16:50:14,859 - [test_register.py-->line:56] - INFO:用例:不输入手机号,执行通过
2020-03-22 16:50:15,093 - [test_register.py-->line:56] - INFO:用例:手机号长度10位,执行通过
2020-03-22 16:50:15,331 - [test_register.py-->line:56] - INFO:用例:手机号长度12位,执行通过
2020-03-22 16:50:15,568 - [test_register.py-->line:56] - INFO:用例:手机号含有非法字符,执行通过
2020-03-22 16:50:15,821 - [test_register.py-->line:56] - INFO:用例:已注册过的手机号,执行通过
2020-03-22 16:50:16,105 - [test_register.py-->line:56] - INFO:用例:密码7位,执行通过
2020-03-22 16:50:16,347 - [test_register.py-->line:56] - INFO:用例:密码17位,执行通过
2020-03-22 16:50:16,577 - [test_register.py-->line:56] - INFO:用例:不输入密码,执行通过
2020-03-22 16:50:16,854 - [test_register.py-->line:56] - INFO:用例:注册名11位,执行通过
2020-03-22 16:50:17,090 - [test_register.py-->line:56] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-22 16:50:17,497 - [test_register.py-->line:56] - INFO:用例:不输入类型,执行通过
2020-03-22 16:50:17,982 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-MemberId为空,执行通过
2020-03-22 16:50:18,115 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount为空,执行通过
2020-03-22 16:50:18,252 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount为负值,执行通过
2020-03-22 16:50:18,421 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount大于500000,执行通过
2020-03-22 16:50:18,563 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount的小数位数多于2位,执行通过
2020-03-22 16:53:02,090 - [test_recharge.py-->line:82] - INFO:用例:充值成功,执行通过
2020-03-22 16:53:02,249 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-MemberId为空,执行通过
2020-03-22 16:53:02,401 - [test_recharge.py-->line:77] - ERROR:用例:充值不成功-Amount为空,执行未通过
2020-03-22 16:53:02,402 - [test_recharge.py-->line:78] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 65, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-22 16:53:02,558 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount为负值,执行通过
2020-03-22 16:53:02,718 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount大于500000,执行通过
2020-03-22 16:53:02,863 - [test_recharge.py-->line:82] - INFO:用例:充值不成功-Amount的小数位数多于2位,执行通过
2020-03-22 16:53:03,224 - [test_recharge.py-->line:82] - INFO:用例:充值成功-Amount的小数位数1位,执行通过
2020-03-22 16:53:03,597 - [test_recharge.py-->line:82] - INFO:用例:充值成功-Amount的小数位数2位,执行通过
2020-03-22 16:53:03,826 - [test_register.py-->line:97] - INFO:用例:登录成功,执行通过
2020-03-22 16:53:03,980 - [test_register.py-->line:91] - ERROR:用例:手机号为空,执行未通过
2020-03-22 16:53:03,980 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-22 16:53:04,167 - [test_register.py-->line:91] - ERROR:用例:密码为空,执行未通过
2020-03-22 16:53:04,167 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-22 16:53:04,346 - [test_register.py-->line:97] - INFO:用例:手机号未注册,执行通过
2020-03-22 16:53:04,516 - [test_register.py-->line:97] - INFO:用例:密码错误,执行通过
2020-03-22 16:53:04,676 - [test_register.py-->line:97] - INFO:用例:手机号格式错误,执行通过
2020-03-22 16:53:05,109 - [test_register.py-->line:56] - INFO:用例:注册成功-带注册名,执行通过
2020-03-22 16:53:05,477 - [test_register.py-->line:56] - INFO:用例:成功-不带用户名,执行通过
2020-03-22 16:53:05,748 - [test_register.py-->line:56] - INFO:用例:不输入手机号,执行通过
2020-03-22 16:53:05,992 - [test_register.py-->line:56] - INFO:用例:手机号长度10位,执行通过
2020-03-22 16:53:06,299 - [test_register.py-->line:56] - INFO:用例:手机号长度12位,执行通过
2020-03-22 16:53:06,572 - [test_register.py-->line:56] - INFO:用例:手机号含有非法字符,执行通过
2020-03-22 16:53:06,826 - [test_register.py-->line:56] - INFO:用例:已注册过的手机号,执行通过
2020-03-22 16:53:07,093 - [test_register.py-->line:56] - INFO:用例:密码7位,执行通过
2020-03-22 16:53:07,409 - [test_register.py-->line:56] - INFO:用例:密码17位,执行通过
2020-03-22 16:53:07,702 - [test_register.py-->line:56] - INFO:用例:不输入密码,执行通过
2020-03-22 16:53:07,990 - [test_register.py-->line:56] - INFO:用例:注册名11位,执行通过
2020-03-22 16:53:08,260 - [test_register.py-->line:56] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-22 16:53:08,746 - [test_register.py-->line:56] - INFO:用例:不输入类型,执行通过
2020-03-22 16:53:09,207 - [test_withdraw.py-->line:79] - INFO:用例:提现成功,执行通过
2020-03-22 16:53:09,327 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-MemberId为空,执行通过
2020-03-22 16:53:09,458 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount为空,执行通过
2020-03-22 16:53:09,635 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount为负值,执行通过
2020-03-22 16:53:09,778 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount大于500000,执行通过
2020-03-22 16:53:09,939 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount的小数位数多于2位,执行通过
2020-03-22 16:53:10,301 - [test_withdraw.py-->line:79] - INFO:用例:提现成功-Amount的小数位数1位,执行通过
2020-03-22 16:53:10,693 - [test_withdraw.py-->line:79] - INFO:用例:提现成功-Amount的小数位数2位,执行通过
2020-03-25 14:52:06,819 - [test_register.py-->line:97] - INFO:用例:登录成功,执行通过
2020-03-25 14:52:06,958 - [test_register.py-->line:91] - ERROR:用例:手机号为空,执行未通过
2020-03-25 14:52:06,959 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-25 14:52:07,086 - [test_register.py-->line:91] - ERROR:用例:密码为空,执行未通过
2020-03-25 14:52:07,086 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-25 14:52:07,257 - [test_register.py-->line:97] - INFO:用例:手机号未注册,执行通过
2020-03-25 14:52:07,420 - [test_register.py-->line:97] - INFO:用例:密码错误,执行通过
2020-03-25 14:52:07,562 - [test_register.py-->line:97] - INFO:用例:手机号格式错误,执行通过
2020-03-25 14:52:08,051 - [test_register.py-->line:56] - INFO:用例:注册成功-带注册名,执行通过
2020-03-25 14:52:08,523 - [test_register.py-->line:56] - INFO:用例:成功-不带用户名,执行通过
2020-03-25 14:52:08,808 - [test_register.py-->line:56] - INFO:用例:不输入手机号,执行通过
2020-03-25 14:52:09,072 - [test_register.py-->line:56] - INFO:用例:手机号长度10位,执行通过
2020-03-25 14:52:09,318 - [test_register.py-->line:56] - INFO:用例:手机号长度12位,执行通过
2020-03-25 14:52:09,563 - [test_register.py-->line:56] - INFO:用例:手机号含有非法字符,执行通过
2020-03-25 14:52:09,866 - [test_register.py-->line:56] - INFO:用例:已注册过的手机号,执行通过
2020-03-25 14:52:10,178 - [test_register.py-->line:56] - INFO:用例:密码7位,执行通过
2020-03-25 14:52:10,461 - [test_register.py-->line:56] - INFO:用例:密码17位,执行通过
2020-03-25 14:52:10,714 - [test_register.py-->line:56] - INFO:用例:不输入密码,执行通过
2020-03-25 14:52:11,019 - [test_register.py-->line:56] - INFO:用例:注册名11位,执行通过
2020-03-25 14:52:11,310 - [test_register.py-->line:56] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-25 14:52:11,779 - [test_register.py-->line:56] - INFO:用例:不输入类型,执行通过
2020-03-25 14:52:12,413 - [test_withdraw.py-->line:79] - INFO:用例:提现成功,执行通过
2020-03-25 14:52:12,617 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-MemberId为空,执行通过
2020-03-25 14:52:12,788 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount为空,执行通过
2020-03-25 14:52:12,935 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount为负值,执行通过
2020-03-25 14:52:13,071 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount大于500000,执行通过
2020-03-25 14:52:13,225 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount的小数位数多于2位,执行通过
2020-03-25 14:52:13,597 - [test_withdraw.py-->line:79] - INFO:用例:提现成功-Amount的小数位数1位,执行通过
2020-03-25 14:52:13,973 - [test_withdraw.py-->line:79] - INFO:用例:提现成功-Amount的小数位数2位,执行通过
2020-03-25 14:54:44,144 - [test_recharge.py-->line:83] - INFO:用例:充值成功,执行通过
2020-03-25 14:54:44,308 - [test_recharge.py-->line:83] - INFO:用例:充值不成功-MemberId为空,执行通过
2020-03-25 14:54:44,512 - [test_recharge.py-->line:78] - ERROR:用例:充值不成功-Amount为空,执行未通过
2020-03-25 14:54:44,512 - [test_recharge.py-->line:79] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 66, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-25 14:54:44,650 - [test_recharge.py-->line:83] - INFO:用例:充值不成功-Amount为负值,执行通过
2020-03-25 14:54:44,885 - [test_recharge.py-->line:83] - INFO:用例:充值不成功-Amount大于500000,执行通过
2020-03-25 14:54:45,113 - [test_recharge.py-->line:83] - INFO:用例:充值不成功-Amount的小数位数多于2位,执行通过
2020-03-25 14:54:45,540 - [test_recharge.py-->line:83] - INFO:用例:充值成功-Amount的小数位数1位,执行通过
2020-03-25 14:54:46,015 - [test_recharge.py-->line:83] - INFO:用例:充值成功-Amount的小数位数2位,执行通过
2020-03-25 14:54:46,337 - [test_register.py-->line:97] - INFO:用例:登录成功,执行通过
2020-03-25 14:54:46,523 - [test_register.py-->line:91] - ERROR:用例:手机号为空,执行未通过
2020-03-25 14:54:46,524 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-25 14:54:46,783 - [test_register.py-->line:91] - ERROR:用例:密码为空,执行未通过
2020-03-25 14:54:46,783 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-25 14:54:46,961 - [test_register.py-->line:97] - INFO:用例:手机号未注册,执行通过
2020-03-25 14:54:47,143 - [test_register.py-->line:97] - INFO:用例:密码错误,执行通过
2020-03-25 14:54:47,317 - [test_register.py-->line:97] - INFO:用例:手机号格式错误,执行通过
2020-03-25 14:54:48,055 - [test_register.py-->line:56] - INFO:用例:注册成功-带注册名,执行通过
2020-03-25 14:54:48,604 - [test_register.py-->line:56] - INFO:用例:成功-不带用户名,执行通过
2020-03-25 14:54:48,861 - [test_register.py-->line:56] - INFO:用例:不输入手机号,执行通过
2020-03-25 14:54:49,179 - [test_register.py-->line:56] - INFO:用例:手机号长度10位,执行通过
2020-03-25 14:54:49,449 - [test_register.py-->line:56] - INFO:用例:手机号长度12位,执行通过
2020-03-25 14:54:49,715 - [test_register.py-->line:56] - INFO:用例:手机号含有非法字符,执行通过
2020-03-25 14:54:50,008 - [test_register.py-->line:56] - INFO:用例:已注册过的手机号,执行通过
2020-03-25 14:54:50,287 - [test_register.py-->line:56] - INFO:用例:密码7位,执行通过
2020-03-25 14:54:50,567 - [test_register.py-->line:56] - INFO:用例:密码17位,执行通过
2020-03-25 14:54:50,896 - [test_register.py-->line:56] - INFO:用例:不输入密码,执行通过
2020-03-25 14:54:51,172 - [test_register.py-->line:56] - INFO:用例:注册名11位,执行通过
2020-03-25 14:54:51,469 - [test_register.py-->line:56] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-25 14:54:51,898 - [test_register.py-->line:56] - INFO:用例:不输入类型,执行通过
2020-03-25 14:54:52,393 - [test_withdraw.py-->line:79] - INFO:用例:提现成功,执行通过
2020-03-25 14:54:52,561 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-MemberId为空,执行通过
2020-03-25 14:54:52,724 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount为空,执行通过
2020-03-25 14:54:52,916 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount为负值,执行通过
2020-03-25 14:54:53,160 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount大于500000,执行通过
2020-03-25 14:54:53,331 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount的小数位数多于2位,执行通过
2020-03-25 14:54:53,702 - [test_withdraw.py-->line:79] - INFO:用例:提现成功-Amount的小数位数1位,执行通过
2020-03-25 14:54:54,988 - [test_withdraw.py-->line:79] - INFO:用例:提现成功-Amount的小数位数2位,执行通过
2020-03-25 21:34:39,389 - [test_recharge.py-->line:83] - INFO:用例:充值成功,执行通过
2020-03-25 21:34:39,546 - [test_recharge.py-->line:83] - INFO:用例:充值不成功-MemberId为空,执行通过
2020-03-25 21:34:39,678 - [test_recharge.py-->line:78] - ERROR:用例:充值不成功-Amount为空,执行未通过
2020-03-25 21:34:39,678 - [test_recharge.py-->line:79] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 66, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-25 21:34:39,805 - [test_recharge.py-->line:83] - INFO:用例:充值不成功-Amount为负值,执行通过
2020-03-25 21:34:39,983 - [test_recharge.py-->line:83] - INFO:用例:充值不成功-Amount大于500000,执行通过
2020-03-25 21:34:40,147 - [test_recharge.py-->line:83] - INFO:用例:充值不成功-Amount的小数位数多于2位,执行通过
2020-03-25 21:34:40,458 - [test_recharge.py-->line:83] - INFO:用例:充值成功-Amount的小数位数1位,执行通过
2020-03-25 21:34:40,855 - [test_recharge.py-->line:83] - INFO:用例:充值成功-Amount的小数位数2位,执行通过
2020-03-25 21:34:41,045 - [test_register.py-->line:97] - INFO:用例:登录成功,执行通过
2020-03-25 21:34:41,193 - [test_register.py-->line:91] - ERROR:用例:手机号为空,执行未通过
2020-03-25 21:34:41,194 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-25 21:34:41,377 - [test_register.py-->line:91] - ERROR:用例:密码为空,执行未通过
2020-03-25 21:34:41,378 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-25 21:34:41,524 - [test_register.py-->line:97] - INFO:用例:手机号未注册,执行通过
2020-03-25 21:34:41,706 - [test_register.py-->line:97] - INFO:用例:密码错误,执行通过
2020-03-25 21:34:41,828 - [test_register.py-->line:97] - INFO:用例:手机号格式错误,执行通过
2020-03-25 21:34:42,318 - [test_register.py-->line:56] - INFO:用例:注册成功-带注册名,执行通过
2020-03-25 21:34:42,733 - [test_register.py-->line:56] - INFO:用例:成功-不带用户名,执行通过
2020-03-25 21:34:42,993 - [test_register.py-->line:56] - INFO:用例:不输入手机号,执行通过
2020-03-25 21:34:43,266 - [test_register.py-->line:56] - INFO:用例:手机号长度10位,执行通过
2020-03-25 21:34:43,530 - [test_register.py-->line:56] - INFO:用例:手机号长度12位,执行通过
2020-03-25 21:34:43,840 - [test_register.py-->line:56] - INFO:用例:手机号含有非法字符,执行通过
2020-03-25 21:34:44,145 - [test_register.py-->line:56] - INFO:用例:已注册过的手机号,执行通过
2020-03-25 21:34:44,433 - [test_register.py-->line:56] - INFO:用例:密码7位,执行通过
2020-03-25 21:34:44,804 - [test_register.py-->line:56] - INFO:用例:密码17位,执行通过
2020-03-25 21:34:45,183 - [test_register.py-->line:56] - INFO:用例:不输入密码,执行通过
2020-03-25 21:34:45,410 - [test_register.py-->line:56] - INFO:用例:注册名11位,执行通过
2020-03-25 21:34:45,651 - [test_register.py-->line:56] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-25 21:34:46,078 - [test_register.py-->line:56] - INFO:用例:不输入类型,执行通过
2020-03-25 21:34:46,547 - [test_withdraw.py-->line:79] - INFO:用例:提现成功,执行通过
2020-03-25 21:34:46,686 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-MemberId为空,执行通过
2020-03-25 21:34:46,846 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount为空,执行通过
2020-03-25 21:34:47,036 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount为负值,执行通过
2020-03-25 21:34:47,202 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount大于500000,执行通过
2020-03-25 21:34:47,334 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount的小数位数多于2位,执行通过
2020-03-25 21:34:47,703 - [test_withdraw.py-->line:79] - INFO:用例:提现成功-Amount的小数位数1位,执行通过
2020-03-25 21:34:48,047 - [test_withdraw.py-->line:79] - INFO:用例:提现成功-Amount的小数位数2位,执行通过
2020-03-29 18:19:06,053 - [test_register.py-->line:97] - INFO:用例:登录成功,执行通过
2020-03-29 18:19:06,813 - [test_register.py-->line:91] - ERROR:用例:手机号为空,执行未通过
2020-03-29 18:19:06,821 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-29 18:19:07,916 - [test_register.py-->line:91] - ERROR:用例:密码为空,执行未通过
2020-03-29 18:19:07,917 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-29 18:19:08,962 - [test_register.py-->line:97] - INFO:用例:手机号未注册,执行通过
2020-03-29 18:19:09,928 - [test_register.py-->line:97] - INFO:用例:密码错误,执行通过
2020-03-29 18:19:10,770 - [test_register.py-->line:97] - INFO:用例:手机号格式错误,执行通过
2020-03-29 18:19:12,105 - [test_register.py-->line:56] - INFO:用例:注册成功-带注册名,执行通过
2020-03-29 18:19:13,410 - [test_register.py-->line:56] - INFO:用例:成功-不带用户名,执行通过
2020-03-29 18:19:14,440 - [test_register.py-->line:56] - INFO:用例:不输入手机号,执行通过
2020-03-29 18:19:15,417 - [test_register.py-->line:56] - INFO:用例:手机号长度10位,执行通过
2020-03-29 18:19:16,466 - [test_register.py-->line:56] - INFO:用例:手机号长度12位,执行通过
2020-03-29 18:19:17,475 - [test_register.py-->line:56] - INFO:用例:手机号含有非法字符,执行通过
2020-03-29 18:19:18,855 - [test_register.py-->line:56] - INFO:用例:已注册过的手机号,执行通过
2020-03-29 18:19:20,126 - [test_register.py-->line:56] - INFO:用例:密码7位,执行通过
2020-03-29 18:19:21,216 - [test_register.py-->line:56] - INFO:用例:密码17位,执行通过
2020-03-29 18:19:22,295 - [test_register.py-->line:56] - INFO:用例:不输入密码,执行通过
2020-03-29 18:19:23,415 - [test_register.py-->line:56] - INFO:用例:注册名11位,执行通过
2020-03-29 18:19:24,783 - [test_register.py-->line:56] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-29 18:19:26,118 - [test_register.py-->line:56] - INFO:用例:不输入类型,执行通过
2020-03-29 18:19:27,544 - [test_withdraw.py-->line:79] - INFO:用例:提现成功,执行通过
2020-03-29 18:19:28,415 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-MemberId为空,执行通过
2020-03-29 18:19:29,347 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount为空,执行通过
2020-03-29 18:19:30,191 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount为负值,执行通过
2020-03-29 18:19:31,023 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount大于500000,执行通过
2020-03-29 18:19:31,731 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount的小数位数多于2位,执行通过
2020-03-29 18:19:32,653 - [test_withdraw.py-->line:74] - ERROR:用例:提现成功-Amount的小数位数1位,执行未通过
2020-03-29 18:19:32,653 - [test_withdraw.py-->line:75] - ERROR:0 != 1002
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_withdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 1002
2020-03-29 18:19:33,687 - [test_withdraw.py-->line:74] - ERROR:用例:提现成功-Amount的小数位数2位,执行未通过
2020-03-29 18:19:33,693 - [test_withdraw.py-->line:75] - ERROR:0 != 1002
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_withdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 1002
2020-03-29 18:48:59,761 - [test_recharge.py-->line:83] - INFO:用例:充值成功,执行通过
2020-03-29 18:48:59,944 - [test_recharge.py-->line:83] - INFO:用例:充值不成功-MemberId为空,执行通过
2020-03-29 18:49:00,097 - [test_recharge.py-->line:78] - ERROR:用例:充值不成功-Amount为空,执行未通过
2020-03-29 18:49:00,097 - [test_recharge.py-->line:79] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 66, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-29 18:49:00,239 - [test_recharge.py-->line:83] - INFO:用例:充值不成功-Amount为负值,执行通过
2020-03-29 18:49:00,406 - [test_recharge.py-->line:83] - INFO:用例:充值不成功-Amount大于500000,执行通过
2020-03-29 18:49:00,558 - [test_recharge.py-->line:83] - INFO:用例:充值不成功-Amount的小数位数多于2位,执行通过
2020-03-29 18:49:01,038 - [test_recharge.py-->line:83] - INFO:用例:充值成功-Amount的小数位数1位,执行通过
2020-03-29 18:49:01,484 - [test_recharge.py-->line:83] - INFO:用例:充值成功-Amount的小数位数2位,执行通过
2020-03-29 18:49:01,850 - [test_register.py-->line:97] - INFO:用例:登录成功,执行通过
2020-03-29 18:49:02,077 - [test_register.py-->line:91] - ERROR:用例:手机号为空,执行未通过
2020-03-29 18:49:02,077 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-29 18:49:02,272 - [test_register.py-->line:91] - ERROR:用例:密码为空,执行未通过
2020-03-29 18:49:02,272 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-03-29 18:49:02,693 - [test_register.py-->line:97] - INFO:用例:手机号未注册,执行通过
2020-03-29 18:49:03,054 - [test_register.py-->line:97] - INFO:用例:密码错误,执行通过
2020-03-29 18:49:03,198 - [test_register.py-->line:97] - INFO:用例:手机号格式错误,执行通过
2020-03-29 18:49:04,057 - [test_register.py-->line:56] - INFO:用例:注册成功-带注册名,执行通过
2020-03-29 18:49:04,914 - [test_register.py-->line:56] - INFO:用例:成功-不带用户名,执行通过
2020-03-29 18:49:05,370 - [test_register.py-->line:56] - INFO:用例:不输入手机号,执行通过
2020-03-29 18:49:05,798 - [test_register.py-->line:56] - INFO:用例:手机号长度10位,执行通过
2020-03-29 18:49:06,327 - [test_register.py-->line:56] - INFO:用例:手机号长度12位,执行通过
2020-03-29 18:49:06,771 - [test_register.py-->line:56] - INFO:用例:手机号含有非法字符,执行通过
2020-03-29 18:49:07,219 - [test_register.py-->line:56] - INFO:用例:已注册过的手机号,执行通过
2020-03-29 18:49:07,638 - [test_register.py-->line:56] - INFO:用例:密码7位,执行通过
2020-03-29 18:49:08,061 - [test_register.py-->line:56] - INFO:用例:密码17位,执行通过
2020-03-29 18:49:08,506 - [test_register.py-->line:56] - INFO:用例:不输入密码,执行通过
2020-03-29 18:49:08,827 - [test_register.py-->line:56] - INFO:用例:注册名11位,执行通过
2020-03-29 18:49:09,359 - [test_register.py-->line:56] - INFO:用例:类型输入非0，1内容,执行通过
2020-03-29 18:49:10,101 - [test_register.py-->line:56] - INFO:用例:不输入类型,执行通过
2020-03-29 18:49:10,774 - [test_withdraw.py-->line:79] - INFO:用例:提现成功,执行通过
2020-03-29 18:49:10,914 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-MemberId为空,执行通过
2020-03-29 18:49:11,067 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount为空,执行通过
2020-03-29 18:49:11,211 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount为负值,执行通过
2020-03-29 18:49:11,326 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount大于500000,执行通过
2020-03-29 18:49:11,544 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount的小数位数多于2位,执行通过
2020-03-29 18:49:12,147 - [test_withdraw.py-->line:79] - INFO:用例:提现成功-Amount的小数位数1位,执行通过
2020-03-29 18:49:12,747 - [test_withdraw.py-->line:79] - INFO:用例:提现成功-Amount的小数位数2位,执行通过
2020-04-08 17:51:08,135 - [test_recharge.py-->line:83] - INFO:用例:充值成功,执行通过
2020-04-08 17:51:08,277 - [test_recharge.py-->line:83] - INFO:用例:充值不成功-MemberId为空,执行通过
2020-04-08 17:51:08,371 - [test_recharge.py-->line:78] - ERROR:用例:充值不成功-Amount为空,执行未通过
2020-04-08 17:51:08,371 - [test_recharge.py-->line:79] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 66, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-04-08 17:51:08,520 - [test_recharge.py-->line:83] - INFO:用例:充值不成功-Amount为负值,执行通过
2020-04-08 17:51:08,634 - [test_recharge.py-->line:83] - INFO:用例:充值不成功-Amount大于500000,执行通过
2020-04-08 17:51:08,739 - [test_recharge.py-->line:83] - INFO:用例:充值不成功-Amount的小数位数多于2位,执行通过
2020-04-08 17:51:09,199 - [test_recharge.py-->line:83] - INFO:用例:充值成功-Amount的小数位数1位,执行通过
2020-04-08 17:51:09,696 - [test_recharge.py-->line:83] - INFO:用例:充值成功-Amount的小数位数2位,执行通过
2020-04-08 17:51:10,049 - [test_register.py-->line:97] - INFO:用例:登录成功,执行通过
2020-04-08 17:51:10,168 - [test_register.py-->line:91] - ERROR:用例:手机号为空,执行未通过
2020-04-08 17:51:10,168 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-04-08 17:51:10,291 - [test_register.py-->line:91] - ERROR:用例:密码为空,执行未通过
2020-04-08 17:51:10,291 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-04-08 17:51:10,606 - [test_register.py-->line:97] - INFO:用例:手机号未注册,执行通过
2020-04-08 17:51:10,882 - [test_register.py-->line:97] - INFO:用例:密码错误,执行通过
2020-04-08 17:51:11,014 - [test_register.py-->line:97] - INFO:用例:手机号格式错误,执行通过
2020-04-08 17:51:11,828 - [test_register.py-->line:56] - INFO:用例:注册成功-带注册名,执行通过
2020-04-08 17:51:12,593 - [test_register.py-->line:56] - INFO:用例:成功-不带用户名,执行通过
2020-04-08 17:51:12,989 - [test_register.py-->line:56] - INFO:用例:不输入手机号,执行通过
2020-04-08 17:51:13,314 - [test_register.py-->line:56] - INFO:用例:手机号长度10位,执行通过
2020-04-08 17:51:13,678 - [test_register.py-->line:56] - INFO:用例:手机号长度12位,执行通过
2020-04-08 17:51:14,084 - [test_register.py-->line:56] - INFO:用例:手机号含有非法字符,执行通过
2020-04-08 17:51:14,572 - [test_register.py-->line:56] - INFO:用例:已注册过的手机号,执行通过
2020-04-08 17:51:14,934 - [test_register.py-->line:56] - INFO:用例:密码7位,执行通过
2020-04-08 17:51:15,253 - [test_register.py-->line:56] - INFO:用例:密码17位,执行通过
2020-04-08 17:51:15,626 - [test_register.py-->line:56] - INFO:用例:不输入密码,执行通过
2020-04-08 17:51:15,968 - [test_register.py-->line:56] - INFO:用例:注册名11位,执行通过
2020-04-08 17:51:16,313 - [test_register.py-->line:56] - INFO:用例:类型输入非0，1内容,执行通过
2020-04-08 17:51:17,097 - [test_register.py-->line:56] - INFO:用例:不输入类型,执行通过
2020-04-08 17:51:17,804 - [test_withdraw.py-->line:79] - INFO:用例:提现成功,执行通过
2020-04-08 17:51:17,933 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-MemberId为空,执行通过
2020-04-08 17:51:18,039 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount为空,执行通过
2020-04-08 17:51:18,163 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount为负值,执行通过
2020-04-08 17:51:18,312 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount大于500000,执行通过
2020-04-08 17:51:18,439 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount的小数位数多于2位,执行通过
2020-04-08 17:51:18,905 - [test_withdraw.py-->line:79] - INFO:用例:提现成功-Amount的小数位数1位,执行通过
2020-04-08 17:51:19,341 - [test_withdraw.py-->line:79] - INFO:用例:提现成功-Amount的小数位数2位,执行通过
2020-04-12 21:09:55,862 - [test_recharge.py-->line:83] - INFO:用例:充值成功,执行通过
2020-04-12 21:09:56,003 - [test_recharge.py-->line:83] - INFO:用例:充值不成功-MemberId为空,执行通过
2020-04-12 21:09:56,151 - [test_recharge.py-->line:78] - ERROR:用例:充值不成功-Amount为空,执行未通过
2020-04-12 21:09:56,152 - [test_recharge.py-->line:79] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 66, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-04-12 21:09:56,348 - [test_recharge.py-->line:83] - INFO:用例:充值不成功-Amount为负值,执行通过
2020-04-12 21:09:56,489 - [test_recharge.py-->line:83] - INFO:用例:充值不成功-Amount大于500000,执行通过
2020-04-12 21:09:56,576 - [test_recharge.py-->line:83] - INFO:用例:充值不成功-Amount的小数位数多于2位,执行通过
2020-04-12 21:09:57,093 - [test_recharge.py-->line:83] - INFO:用例:充值成功-Amount的小数位数1位,执行通过
2020-04-12 21:09:57,530 - [test_recharge.py-->line:83] - INFO:用例:充值成功-Amount的小数位数2位,执行通过
2020-04-12 21:09:57,875 - [test_register.py-->line:97] - INFO:用例:登录成功,执行通过
2020-04-12 21:09:57,965 - [test_register.py-->line:91] - ERROR:用例:手机号为空,执行未通过
2020-04-12 21:09:57,965 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-04-12 21:09:58,123 - [test_register.py-->line:91] - ERROR:用例:密码为空,执行未通过
2020-04-12 21:09:58,123 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-04-12 21:09:58,464 - [test_register.py-->line:97] - INFO:用例:手机号未注册,执行通过
2020-04-12 21:09:58,789 - [test_register.py-->line:97] - INFO:用例:密码错误,执行通过
2020-04-12 21:09:58,965 - [test_register.py-->line:97] - INFO:用例:手机号格式错误,执行通过
2020-04-12 21:09:59,755 - [test_register.py-->line:56] - INFO:用例:注册成功-带注册名,执行通过
2020-04-12 21:10:00,534 - [test_register.py-->line:56] - INFO:用例:成功-不带用户名,执行通过
2020-04-12 21:10:00,932 - [test_register.py-->line:56] - INFO:用例:不输入手机号,执行通过
2020-04-12 21:10:01,301 - [test_register.py-->line:56] - INFO:用例:手机号长度10位,执行通过
2020-04-12 21:10:01,661 - [test_register.py-->line:56] - INFO:用例:手机号长度12位,执行通过
2020-04-12 21:10:02,064 - [test_register.py-->line:56] - INFO:用例:手机号含有非法字符,执行通过
2020-04-12 21:10:02,688 - [test_register.py-->line:56] - INFO:用例:已注册过的手机号,执行通过
2020-04-12 21:10:03,071 - [test_register.py-->line:56] - INFO:用例:密码7位,执行通过
2020-04-12 21:10:03,471 - [test_register.py-->line:56] - INFO:用例:密码17位,执行通过
2020-04-12 21:10:03,845 - [test_register.py-->line:56] - INFO:用例:不输入密码,执行通过
2020-04-12 21:10:04,217 - [test_register.py-->line:56] - INFO:用例:注册名11位,执行通过
2020-04-12 21:10:04,620 - [test_register.py-->line:56] - INFO:用例:类型输入非0，1内容,执行通过
2020-04-12 21:10:05,440 - [test_register.py-->line:56] - INFO:用例:不输入类型,执行通过
2020-04-12 21:10:06,154 - [test_withdraw.py-->line:79] - INFO:用例:提现成功,执行通过
2020-04-12 21:10:06,239 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-MemberId为空,执行通过
2020-04-12 21:10:06,338 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount为空,执行通过
2020-04-12 21:10:06,466 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount为负值,执行通过
2020-04-12 21:10:06,601 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount大于500000,执行通过
2020-04-12 21:10:06,687 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount的小数位数多于2位,执行通过
2020-04-12 21:10:07,182 - [test_withdraw.py-->line:79] - INFO:用例:提现成功-Amount的小数位数1位,执行通过
2020-04-12 21:10:07,684 - [test_withdraw.py-->line:79] - INFO:用例:提现成功-Amount的小数位数2位,执行通过
2020-04-14 21:32:04,372 - [test_recharge.py-->line:83] - INFO:用例:充值不成功-MemberId为空,执行通过
2020-04-14 21:32:04,537 - [test_register.py-->line:97] - INFO:用例:登录成功,执行通过
2020-04-14 21:32:04,657 - [test_register.py-->line:91] - ERROR:用例:手机号为空,执行未通过
2020-04-14 21:32:04,657 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-04-14 21:32:04,840 - [test_register.py-->line:91] - ERROR:用例:密码为空,执行未通过
2020-04-14 21:32:04,841 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-04-14 21:32:05,271 - [test_register.py-->line:97] - INFO:用例:手机号未注册,执行通过
2020-04-14 21:32:05,669 - [test_register.py-->line:97] - INFO:用例:密码错误,执行通过
2020-04-14 21:32:05,820 - [test_register.py-->line:97] - INFO:用例:手机号格式错误,执行通过
2020-04-14 21:32:06,604 - [test_register.py-->line:56] - INFO:用例:注册成功-带注册名,执行通过
2020-04-14 21:32:07,358 - [test_register.py-->line:56] - INFO:用例:成功-不带用户名,执行通过
2020-04-14 21:32:07,719 - [test_register.py-->line:56] - INFO:用例:不输入手机号,执行通过
2020-04-14 21:32:08,096 - [test_register.py-->line:56] - INFO:用例:手机号长度10位,执行通过
2020-04-14 21:32:08,496 - [test_register.py-->line:56] - INFO:用例:手机号长度12位,执行通过
2020-04-14 21:32:08,868 - [test_register.py-->line:56] - INFO:用例:手机号含有非法字符,执行通过
2020-04-14 21:32:09,408 - [test_register.py-->line:56] - INFO:用例:已注册过的手机号,执行通过
2020-04-14 21:32:09,748 - [test_register.py-->line:56] - INFO:用例:密码7位,执行通过
2020-04-14 21:32:10,105 - [test_register.py-->line:56] - INFO:用例:密码17位,执行通过
2020-04-14 21:32:10,460 - [test_register.py-->line:56] - INFO:用例:不输入密码,执行通过
2020-04-14 21:32:10,822 - [test_register.py-->line:56] - INFO:用例:注册名11位,执行通过
2020-04-14 21:32:11,163 - [test_register.py-->line:56] - INFO:用例:类型输入非0，1内容,执行通过
2020-04-14 21:32:11,896 - [test_register.py-->line:56] - INFO:用例:不输入类型,执行通过
2020-04-14 21:32:12,605 - [test_withdraw.py-->line:79] - INFO:用例:提现成功,执行通过
2020-04-14 21:32:12,724 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-MemberId为空,执行通过
2020-04-14 21:32:12,843 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount为空,执行通过
2020-04-14 21:32:12,969 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount为负值,执行通过
2020-04-14 21:32:13,092 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount大于500000,执行通过
2020-04-14 21:32:13,258 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount的小数位数多于2位,执行通过
2020-04-14 21:32:13,886 - [test_withdraw.py-->line:79] - INFO:用例:提现成功-Amount的小数位数1位,执行通过
2020-04-14 21:32:14,533 - [test_withdraw.py-->line:79] - INFO:用例:提现成功-Amount的小数位数2位,执行通过
2020-04-14 21:34:53,900 - [test_recharge.py-->line:83] - INFO:用例:充值成功,执行通过
2020-04-14 21:34:54,009 - [test_recharge.py-->line:83] - INFO:用例:充值不成功-MemberId为空,执行通过
2020-04-14 21:34:54,120 - [test_recharge.py-->line:78] - ERROR:用例:充值不成功-Amount为空,执行未通过
2020-04-14 21:34:54,120 - [test_recharge.py-->line:79] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_recharge.py", line 66, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-04-14 21:34:54,240 - [test_recharge.py-->line:83] - INFO:用例:充值不成功-Amount为负值,执行通过
2020-04-14 21:34:54,405 - [test_recharge.py-->line:83] - INFO:用例:充值不成功-Amount大于500000,执行通过
2020-04-14 21:34:54,559 - [test_recharge.py-->line:83] - INFO:用例:充值不成功-Amount的小数位数多于2位,执行通过
2020-04-14 21:34:55,011 - [test_recharge.py-->line:83] - INFO:用例:充值成功-Amount的小数位数1位,执行通过
2020-04-14 21:34:55,458 - [test_recharge.py-->line:83] - INFO:用例:充值成功-Amount的小数位数2位,执行通过
2020-04-14 21:34:55,826 - [test_register.py-->line:97] - INFO:用例:登录成功,执行通过
2020-04-14 21:34:55,938 - [test_register.py-->line:91] - ERROR:用例:手机号为空,执行未通过
2020-04-14 21:34:55,938 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-04-14 21:34:56,049 - [test_register.py-->line:91] - ERROR:用例:密码为空,执行未通过
2020-04-14 21:34:56,049 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python4\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-04-14 21:34:56,354 - [test_register.py-->line:97] - INFO:用例:手机号未注册,执行通过
2020-04-14 21:34:56,693 - [test_register.py-->line:97] - INFO:用例:密码错误,执行通过
2020-04-14 21:34:56,820 - [test_register.py-->line:97] - INFO:用例:手机号格式错误,执行通过
2020-04-14 21:34:57,612 - [test_register.py-->line:56] - INFO:用例:注册成功-带注册名,执行通过
2020-04-14 21:34:58,361 - [test_register.py-->line:56] - INFO:用例:成功-不带用户名,执行通过
2020-04-14 21:34:58,756 - [test_register.py-->line:56] - INFO:用例:不输入手机号,执行通过
2020-04-14 21:34:59,117 - [test_register.py-->line:56] - INFO:用例:手机号长度10位,执行通过
2020-04-14 21:34:59,478 - [test_register.py-->line:56] - INFO:用例:手机号长度12位,执行通过
2020-04-14 21:34:59,886 - [test_register.py-->line:56] - INFO:用例:手机号含有非法字符,执行通过
2020-04-14 21:35:00,379 - [test_register.py-->line:56] - INFO:用例:已注册过的手机号,执行通过
2020-04-14 21:35:00,771 - [test_register.py-->line:56] - INFO:用例:密码7位,执行通过
2020-04-14 21:35:01,120 - [test_register.py-->line:56] - INFO:用例:密码17位,执行通过
2020-04-14 21:35:01,473 - [test_register.py-->line:56] - INFO:用例:不输入密码,执行通过
2020-04-14 21:35:01,846 - [test_register.py-->line:56] - INFO:用例:注册名11位,执行通过
2020-04-14 21:35:02,207 - [test_register.py-->line:56] - INFO:用例:类型输入非0，1内容,执行通过
2020-04-14 21:35:02,946 - [test_register.py-->line:56] - INFO:用例:不输入类型,执行通过
2020-04-14 21:35:03,704 - [test_withdraw.py-->line:79] - INFO:用例:提现成功,执行通过
2020-04-14 21:35:03,848 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-MemberId为空,执行通过
2020-04-14 21:35:03,981 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount为空,执行通过
2020-04-14 21:35:04,141 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount为负值,执行通过
2020-04-14 21:35:04,266 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount大于500000,执行通过
2020-04-14 21:35:04,388 - [test_withdraw.py-->line:79] - INFO:用例:提现不成功-Amount的小数位数多于2位,执行通过
2020-04-14 21:35:04,837 - [test_withdraw.py-->line:79] - INFO:用例:提现成功-Amount的小数位数1位,执行通过
2020-04-14 21:35:05,277 - [test_withdraw.py-->line:79] - INFO:用例:提现成功-Amount的小数位数2位,执行通过
2020-04-19 16:38:50,337 - [test_recharge.py-->line:81] - ERROR:用例:充值成功,执行未通过
2020-04-19 16:38:50,338 - [test_recharge.py-->line:82] - ERROR:0 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_recharge.py", line 69, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 1003
2020-04-19 16:38:50,493 - [test_recharge.py-->line:81] - ERROR:用例:充值不成功-MemberId为空,执行未通过
2020-04-19 16:38:50,493 - [test_recharge.py-->line:82] - ERROR:1 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_recharge.py", line 69, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 1003
2020-04-19 16:38:50,652 - [test_recharge.py-->line:81] - ERROR:用例:充值不成功-Amount为空,执行未通过
2020-04-19 16:38:50,652 - [test_recharge.py-->line:82] - ERROR:1 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_recharge.py", line 69, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 1003
2020-04-19 16:38:50,860 - [test_recharge.py-->line:81] - ERROR:用例:充值不成功-Amount为负值,执行未通过
2020-04-19 16:38:50,860 - [test_recharge.py-->line:82] - ERROR:2 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_recharge.py", line 69, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 1003
2020-04-19 16:38:51,035 - [test_recharge.py-->line:81] - ERROR:用例:充值不成功-Amount大于500000,执行未通过
2020-04-19 16:38:51,036 - [test_recharge.py-->line:82] - ERROR:2 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_recharge.py", line 69, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 1003
2020-04-19 16:38:51,238 - [test_recharge.py-->line:81] - ERROR:用例:充值不成功-Amount的小数位数多于2位,执行未通过
2020-04-19 16:38:51,239 - [test_recharge.py-->line:82] - ERROR:2 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_recharge.py", line 69, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 1003
2020-04-19 16:38:51,596 - [test_recharge.py-->line:81] - ERROR:用例:充值成功-Amount的小数位数1位,执行未通过
2020-04-19 16:38:51,597 - [test_recharge.py-->line:82] - ERROR:0 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_recharge.py", line 69, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 1003
2020-04-19 16:38:51,978 - [test_recharge.py-->line:81] - ERROR:用例:充值成功-Amount的小数位数2位,执行未通过
2020-04-19 16:38:51,978 - [test_recharge.py-->line:82] - ERROR:0 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_recharge.py", line 69, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 1003
2020-04-19 16:38:52,155 - [test_register.py-->line:97] - INFO:用例:登录成功,执行通过
2020-04-19 16:38:52,324 - [test_register.py-->line:91] - ERROR:用例:手机号为空,执行未通过
2020-04-19 16:38:52,324 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-04-19 16:38:52,477 - [test_register.py-->line:91] - ERROR:用例:密码为空,执行未通过
2020-04-19 16:38:52,477 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-04-19 16:38:52,802 - [test_register.py-->line:97] - INFO:用例:手机号未注册,执行通过
2020-04-19 16:38:53,107 - [test_register.py-->line:97] - INFO:用例:密码错误,执行通过
2020-04-19 16:38:53,282 - [test_register.py-->line:97] - INFO:用例:手机号格式错误,执行通过
2020-04-19 16:38:54,100 - [test_register.py-->line:56] - INFO:用例:注册成功-带注册名,执行通过
2020-04-19 16:38:54,870 - [test_register.py-->line:56] - INFO:用例:成功-不带用户名,执行通过
2020-04-19 16:38:55,237 - [test_register.py-->line:56] - INFO:用例:不输入手机号,执行通过
2020-04-19 16:38:55,604 - [test_register.py-->line:56] - INFO:用例:手机号长度10位,执行通过
2020-04-19 16:38:56,019 - [test_register.py-->line:56] - INFO:用例:手机号长度12位,执行通过
2020-04-19 16:38:56,393 - [test_register.py-->line:56] - INFO:用例:手机号含有非法字符,执行通过
2020-04-19 16:38:56,975 - [test_register.py-->line:56] - INFO:用例:已注册过的手机号,执行通过
2020-04-19 16:38:57,363 - [test_register.py-->line:56] - INFO:用例:密码7位,执行通过
2020-04-19 16:38:57,734 - [test_register.py-->line:56] - INFO:用例:密码17位,执行通过
2020-04-19 16:38:58,120 - [test_register.py-->line:56] - INFO:用例:不输入密码,执行通过
2020-04-19 16:38:58,519 - [test_register.py-->line:56] - INFO:用例:注册名11位,执行通过
2020-04-19 16:38:58,989 - [test_register.py-->line:56] - INFO:用例:类型输入非0，1内容,执行通过
2020-04-19 16:38:59,842 - [test_register.py-->line:56] - INFO:用例:不输入类型,执行通过
2020-04-19 16:39:00,397 - [test_withdraw.py-->line:74] - ERROR:用例:提现成功,执行未通过
2020-04-19 16:39:00,398 - [test_withdraw.py-->line:75] - ERROR:0 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_withdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 1003
2020-04-19 16:39:00,558 - [test_withdraw.py-->line:74] - ERROR:用例:提现不成功-MemberId为空,执行未通过
2020-04-19 16:39:00,558 - [test_withdraw.py-->line:75] - ERROR:1 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_withdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 1003
2020-04-19 16:39:00,722 - [test_withdraw.py-->line:74] - ERROR:用例:提现不成功-Amount为空,执行未通过
2020-04-19 16:39:00,723 - [test_withdraw.py-->line:75] - ERROR:1 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_withdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 1003
2020-04-19 16:39:00,911 - [test_withdraw.py-->line:74] - ERROR:用例:提现不成功-Amount为负值,执行未通过
2020-04-19 16:39:00,912 - [test_withdraw.py-->line:75] - ERROR:2 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_withdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 1003
2020-04-19 16:39:01,080 - [test_withdraw.py-->line:74] - ERROR:用例:提现不成功-Amount大于500000,执行未通过
2020-04-19 16:39:01,080 - [test_withdraw.py-->line:75] - ERROR:2 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_withdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 1003
2020-04-19 16:39:01,236 - [test_withdraw.py-->line:74] - ERROR:用例:提现不成功-Amount的小数位数多于2位,执行未通过
2020-04-19 16:39:01,236 - [test_withdraw.py-->line:75] - ERROR:2 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_withdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 1003
2020-04-19 16:39:01,568 - [test_withdraw.py-->line:74] - ERROR:用例:提现成功-Amount的小数位数1位,执行未通过
2020-04-19 16:39:01,568 - [test_withdraw.py-->line:75] - ERROR:0 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_withdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 1003
2020-04-19 16:39:01,863 - [test_withdraw.py-->line:74] - ERROR:用例:提现成功-Amount的小数位数2位,执行未通过
2020-04-19 16:39:01,863 - [test_withdraw.py-->line:75] - ERROR:0 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_withdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 1003
2020-04-19 16:48:16,520 - [test_recharge.py-->line:81] - ERROR:用例:充值成功,执行未通过
2020-04-19 16:48:16,520 - [test_recharge.py-->line:82] - ERROR:0 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_recharge.py", line 69, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 1003
2020-04-19 16:48:16,687 - [test_recharge.py-->line:81] - ERROR:用例:充值不成功-MemberId为空,执行未通过
2020-04-19 16:48:16,687 - [test_recharge.py-->line:82] - ERROR:1 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_recharge.py", line 69, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 1003
2020-04-19 16:48:16,859 - [test_recharge.py-->line:81] - ERROR:用例:充值不成功-Amount为空,执行未通过
2020-04-19 16:48:16,859 - [test_recharge.py-->line:82] - ERROR:1 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_recharge.py", line 69, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 1003
2020-04-19 16:48:17,021 - [test_recharge.py-->line:81] - ERROR:用例:充值不成功-Amount为负值,执行未通过
2020-04-19 16:48:17,021 - [test_recharge.py-->line:82] - ERROR:2 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_recharge.py", line 69, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 1003
2020-04-19 16:48:17,191 - [test_recharge.py-->line:81] - ERROR:用例:充值不成功-Amount大于500000,执行未通过
2020-04-19 16:48:17,191 - [test_recharge.py-->line:82] - ERROR:2 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_recharge.py", line 69, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 1003
2020-04-19 16:48:17,454 - [test_recharge.py-->line:81] - ERROR:用例:充值不成功-Amount的小数位数多于2位,执行未通过
2020-04-19 16:48:17,454 - [test_recharge.py-->line:82] - ERROR:2 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_recharge.py", line 69, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 1003
2020-04-19 16:48:17,777 - [test_recharge.py-->line:81] - ERROR:用例:充值成功-Amount的小数位数1位,执行未通过
2020-04-19 16:48:17,777 - [test_recharge.py-->line:82] - ERROR:0 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_recharge.py", line 69, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 1003
2020-04-19 16:48:18,104 - [test_recharge.py-->line:81] - ERROR:用例:充值成功-Amount的小数位数2位,执行未通过
2020-04-19 16:48:18,104 - [test_recharge.py-->line:82] - ERROR:0 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_recharge.py", line 69, in test_recharge
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 1003
2020-04-19 16:48:18,281 - [test_register.py-->line:97] - INFO:用例:登录成功,执行通过
2020-04-19 16:48:18,554 - [test_register.py-->line:91] - ERROR:用例:手机号为空,执行未通过
2020-04-19 16:48:18,554 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-04-19 16:48:18,714 - [test_register.py-->line:91] - ERROR:用例:密码为空,执行未通过
2020-04-19 16:48:18,714 - [test_register.py-->line:92] - ERROR:1 != 2
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_register.py", line 85, in test_login
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-04-19 16:48:19,060 - [test_register.py-->line:97] - INFO:用例:手机号未注册,执行通过
2020-04-19 16:48:19,413 - [test_register.py-->line:97] - INFO:用例:密码错误,执行通过
2020-04-19 16:48:19,690 - [test_register.py-->line:97] - INFO:用例:手机号格式错误,执行通过
2020-04-19 16:48:20,535 - [test_register.py-->line:56] - INFO:用例:注册成功-带注册名,执行通过
2020-04-19 16:48:21,323 - [test_register.py-->line:56] - INFO:用例:成功-不带用户名,执行通过
2020-04-19 16:48:21,769 - [test_register.py-->line:56] - INFO:用例:不输入手机号,执行通过
2020-04-19 16:48:22,150 - [test_register.py-->line:56] - INFO:用例:手机号长度10位,执行通过
2020-04-19 16:48:22,549 - [test_register.py-->line:56] - INFO:用例:手机号长度12位,执行通过
2020-04-19 16:48:22,986 - [test_register.py-->line:56] - INFO:用例:手机号含有非法字符,执行通过
2020-04-19 16:48:23,581 - [test_register.py-->line:56] - INFO:用例:已注册过的手机号,执行通过
2020-04-19 16:48:24,001 - [test_register.py-->line:56] - INFO:用例:密码7位,执行通过
2020-04-19 16:48:24,394 - [test_register.py-->line:56] - INFO:用例:密码17位,执行通过
2020-04-19 16:48:24,771 - [test_register.py-->line:56] - INFO:用例:不输入密码,执行通过
2020-04-19 16:48:25,171 - [test_register.py-->line:56] - INFO:用例:注册名11位,执行通过
2020-04-19 16:48:25,552 - [test_register.py-->line:56] - INFO:用例:类型输入非0，1内容,执行通过
2020-04-19 16:48:26,325 - [test_register.py-->line:56] - INFO:用例:不输入类型,执行通过
2020-04-19 16:48:26,878 - [test_withdraw.py-->line:74] - ERROR:用例:提现成功,执行未通过
2020-04-19 16:48:26,878 - [test_withdraw.py-->line:75] - ERROR:0 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_withdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 1003
2020-04-19 16:48:27,030 - [test_withdraw.py-->line:74] - ERROR:用例:提现不成功-MemberId为空,执行未通过
2020-04-19 16:48:27,031 - [test_withdraw.py-->line:75] - ERROR:1 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_withdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 1003
2020-04-19 16:48:27,216 - [test_withdraw.py-->line:74] - ERROR:用例:提现不成功-Amount为空,执行未通过
2020-04-19 16:48:27,216 - [test_withdraw.py-->line:75] - ERROR:1 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_withdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 1003
2020-04-19 16:48:27,367 - [test_withdraw.py-->line:74] - ERROR:用例:提现不成功-Amount为负值,执行未通过
2020-04-19 16:48:27,368 - [test_withdraw.py-->line:75] - ERROR:2 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_withdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 1003
2020-04-19 16:48:27,524 - [test_withdraw.py-->line:74] - ERROR:用例:提现不成功-Amount大于500000,执行未通过
2020-04-19 16:48:27,524 - [test_withdraw.py-->line:75] - ERROR:2 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_withdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 1003
2020-04-19 16:48:27,690 - [test_withdraw.py-->line:74] - ERROR:用例:提现不成功-Amount的小数位数多于2位,执行未通过
2020-04-19 16:48:27,691 - [test_withdraw.py-->line:75] - ERROR:2 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_withdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 1003
2020-04-19 16:48:27,998 - [test_withdraw.py-->line:74] - ERROR:用例:提现成功-Amount的小数位数1位,执行未通过
2020-04-19 16:48:27,998 - [test_withdraw.py-->line:75] - ERROR:0 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_withdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 1003
2020-04-19 16:48:28,392 - [test_withdraw.py-->line:74] - ERROR:用例:提现成功-Amount的小数位数2位,执行未通过
2020-04-19 16:48:28,392 - [test_withdraw.py-->line:75] - ERROR:0 != 1003
Traceback (most recent call last):
  File "c:\wsl\AutoTest\auto_python5_V3\testcases\test_withdraw.py", line 63, in test_withdraw
    self.assertEqual(expected["code"],res["code"])
  File "C:\python3\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\python3\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 1003
